// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <control_msgs/action/follow_joint_trajectory.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("control_msgs/FollowJointTrajectory_SendGoal", FollowJointTrajectory_SendGoalTypeSupport)
	typemap.RegisterService("control_msgs/action/FollowJointTrajectory_SendGoal", FollowJointTrajectory_SendGoalTypeSupport)
}

type _FollowJointTrajectory_SendGoalTypeSupport struct {}

func (s _FollowJointTrajectory_SendGoalTypeSupport) Request() types.MessageTypeSupport {
	return FollowJointTrajectory_SendGoal_RequestTypeSupport
}

func (s _FollowJointTrajectory_SendGoalTypeSupport) Response() types.MessageTypeSupport {
	return FollowJointTrajectory_SendGoal_ResponseTypeSupport
}

func (s _FollowJointTrajectory_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__control_msgs__action__FollowJointTrajectory_SendGoal())
}

// Modifying this variable is undefined behavior.
var FollowJointTrajectory_SendGoalTypeSupport types.ServiceTypeSupport = _FollowJointTrajectory_SendGoalTypeSupport{}

// FollowJointTrajectory_SendGoalClient wraps rclgo.Client to provide type safe helper
// functions
type FollowJointTrajectory_SendGoalClient struct {
	*rclgo.Client
}

// NewFollowJointTrajectory_SendGoalClient creates and returns a new client for the
// FollowJointTrajectory_SendGoal
func NewFollowJointTrajectory_SendGoalClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*FollowJointTrajectory_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, FollowJointTrajectory_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowJointTrajectory_SendGoalClient{client}, nil
}

func (s *FollowJointTrajectory_SendGoalClient) Send(ctx context.Context, req *FollowJointTrajectory_SendGoal_Request) (*FollowJointTrajectory_SendGoal_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FollowJointTrajectory_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FollowJointTrajectory_SendGoalServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s FollowJointTrajectory_SendGoalServiceResponseSender) SendResponse(resp *FollowJointTrajectory_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type FollowJointTrajectory_SendGoalServiceRequestHandler func(*rclgo.ServiceInfo, *FollowJointTrajectory_SendGoal_Request, FollowJointTrajectory_SendGoalServiceResponseSender)

// FollowJointTrajectory_SendGoalService wraps rclgo.Service to provide type safe helper
// functions
type FollowJointTrajectory_SendGoalService struct {
	*rclgo.Service
}

// NewFollowJointTrajectory_SendGoalService creates and returns a new service for the
// FollowJointTrajectory_SendGoal
func NewFollowJointTrajectory_SendGoalService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler FollowJointTrajectory_SendGoalServiceRequestHandler) (*FollowJointTrajectory_SendGoalService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*FollowJointTrajectory_SendGoal_Request)
		responseSender := FollowJointTrajectory_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FollowJointTrajectory_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FollowJointTrajectory_SendGoalService{service}, nil
}