// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/follow_joint_trajectory.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/FollowJointTrajectory_FeedbackMessage", FollowJointTrajectory_FeedbackMessageTypeSupport)
	typemap.RegisterMessage("control_msgs/action/FollowJointTrajectory_FeedbackMessage", FollowJointTrajectory_FeedbackMessageTypeSupport)
}

type FollowJointTrajectory_FeedbackMessage struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Feedback FollowJointTrajectory_Feedback `yaml:"feedback"`
}

// NewFollowJointTrajectory_FeedbackMessage creates a new FollowJointTrajectory_FeedbackMessage with default values.
func NewFollowJointTrajectory_FeedbackMessage() *FollowJointTrajectory_FeedbackMessage {
	self := FollowJointTrajectory_FeedbackMessage{}
	self.SetDefaults()
	return &self
}

func (t *FollowJointTrajectory_FeedbackMessage) Clone() *FollowJointTrajectory_FeedbackMessage {
	c := &FollowJointTrajectory_FeedbackMessage{}
	c.GoalID = *t.GoalID.Clone()
	c.Feedback = *t.Feedback.Clone()
	return c
}

func (t *FollowJointTrajectory_FeedbackMessage) CloneMsg() types.Message {
	return t.Clone()
}

func (t *FollowJointTrajectory_FeedbackMessage) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Feedback.SetDefaults()
}

func (t *FollowJointTrajectory_FeedbackMessage) GetTypeSupport() types.MessageTypeSupport {
	return FollowJointTrajectory_FeedbackMessageTypeSupport
}
func (t *FollowJointTrajectory_FeedbackMessage) GetGoalID() *types.GoalID {
	return (*types.GoalID)(&t.GoalID.Uuid)
}

func (t *FollowJointTrajectory_FeedbackMessage) SetGoalID(id *types.GoalID) {
	t.GoalID.Uuid = *id
}

// FollowJointTrajectory_FeedbackMessagePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type FollowJointTrajectory_FeedbackMessagePublisher struct {
	*rclgo.Publisher
}

// NewFollowJointTrajectory_FeedbackMessagePublisher creates and returns a new publisher for the
// FollowJointTrajectory_FeedbackMessage
func NewFollowJointTrajectory_FeedbackMessagePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*FollowJointTrajectory_FeedbackMessagePublisher, error) {
	pub, err := node.NewPublisher(topic_name, FollowJointTrajectory_FeedbackMessageTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowJointTrajectory_FeedbackMessagePublisher{pub}, nil
}

func (p *FollowJointTrajectory_FeedbackMessagePublisher) Publish(msg *FollowJointTrajectory_FeedbackMessage) error {
	return p.Publisher.Publish(msg)
}

// FollowJointTrajectory_FeedbackMessageSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type FollowJointTrajectory_FeedbackMessageSubscription struct {
	*rclgo.Subscription
}

// FollowJointTrajectory_FeedbackMessageSubscriptionCallback type is used to provide a subscription
// handler function for a FollowJointTrajectory_FeedbackMessageSubscription.
type FollowJointTrajectory_FeedbackMessageSubscriptionCallback func(msg *FollowJointTrajectory_FeedbackMessage, info *rclgo.MessageInfo, err error)

// NewFollowJointTrajectory_FeedbackMessageSubscription creates and returns a new subscription for the
// FollowJointTrajectory_FeedbackMessage
func NewFollowJointTrajectory_FeedbackMessageSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback FollowJointTrajectory_FeedbackMessageSubscriptionCallback) (*FollowJointTrajectory_FeedbackMessageSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg FollowJointTrajectory_FeedbackMessage
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, FollowJointTrajectory_FeedbackMessageTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FollowJointTrajectory_FeedbackMessageSubscription{sub}, nil
}

func (s *FollowJointTrajectory_FeedbackMessageSubscription) TakeMessage(out *FollowJointTrajectory_FeedbackMessage) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFollowJointTrajectory_FeedbackMessageSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFollowJointTrajectory_FeedbackMessageSlice(dst, src []FollowJointTrajectory_FeedbackMessage) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FollowJointTrajectory_FeedbackMessageTypeSupport types.MessageTypeSupport = _FollowJointTrajectory_FeedbackMessageTypeSupport{}

type _FollowJointTrajectory_FeedbackMessageTypeSupport struct{}

func (t _FollowJointTrajectory_FeedbackMessageTypeSupport) New() types.Message {
	return NewFollowJointTrajectory_FeedbackMessage()
}

func (t _FollowJointTrajectory_FeedbackMessageTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__FollowJointTrajectory_FeedbackMessage
	return (unsafe.Pointer)(C.control_msgs__action__FollowJointTrajectory_FeedbackMessage__create())
}

func (t _FollowJointTrajectory_FeedbackMessageTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__FollowJointTrajectory_FeedbackMessage__destroy((*C.control_msgs__action__FollowJointTrajectory_FeedbackMessage)(pointer_to_free))
}

func (t _FollowJointTrajectory_FeedbackMessageTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FollowJointTrajectory_FeedbackMessage)
	mem := (*C.control_msgs__action__FollowJointTrajectory_FeedbackMessage)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	FollowJointTrajectory_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&mem.feedback), &m.Feedback)
}

func (t _FollowJointTrajectory_FeedbackMessageTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FollowJointTrajectory_FeedbackMessage)
	mem := (*C.control_msgs__action__FollowJointTrajectory_FeedbackMessage)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	FollowJointTrajectory_FeedbackTypeSupport.AsGoStruct(&m.Feedback, unsafe.Pointer(&mem.feedback))
}

func (t _FollowJointTrajectory_FeedbackMessageTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__FollowJointTrajectory_FeedbackMessage())
}

type CFollowJointTrajectory_FeedbackMessage = C.control_msgs__action__FollowJointTrajectory_FeedbackMessage
type CFollowJointTrajectory_FeedbackMessage__Sequence = C.control_msgs__action__FollowJointTrajectory_FeedbackMessage__Sequence

func FollowJointTrajectory_FeedbackMessage__Sequence_to_Go(goSlice *[]FollowJointTrajectory_FeedbackMessage, cSlice CFollowJointTrajectory_FeedbackMessage__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FollowJointTrajectory_FeedbackMessage, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FollowJointTrajectory_FeedbackMessageTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func FollowJointTrajectory_FeedbackMessage__Sequence_to_C(cSlice *CFollowJointTrajectory_FeedbackMessage__Sequence, goSlice []FollowJointTrajectory_FeedbackMessage) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__FollowJointTrajectory_FeedbackMessage)(C.malloc(C.sizeof_struct_control_msgs__action__FollowJointTrajectory_FeedbackMessage * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FollowJointTrajectory_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func FollowJointTrajectory_FeedbackMessage__Array_to_Go(goSlice []FollowJointTrajectory_FeedbackMessage, cSlice []CFollowJointTrajectory_FeedbackMessage) {
	for i := 0; i < len(cSlice); i++ {
		FollowJointTrajectory_FeedbackMessageTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FollowJointTrajectory_FeedbackMessage__Array_to_C(cSlice []CFollowJointTrajectory_FeedbackMessage, goSlice []FollowJointTrajectory_FeedbackMessage) {
	for i := 0; i < len(goSlice); i++ {
		FollowJointTrajectory_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
