// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/gripper_command.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/GripperCommand_SendGoal_Response", GripperCommand_SendGoal_ResponseTypeSupport)
	typemap.RegisterMessage("control_msgs/action/GripperCommand_SendGoal_Response", GripperCommand_SendGoal_ResponseTypeSupport)
}

type GripperCommand_SendGoal_Response struct {
	Accepted bool `yaml:"accepted"`
	Stamp builtin_interfaces_msg.Time `yaml:"stamp"`
}

// NewGripperCommand_SendGoal_Response creates a new GripperCommand_SendGoal_Response with default values.
func NewGripperCommand_SendGoal_Response() *GripperCommand_SendGoal_Response {
	self := GripperCommand_SendGoal_Response{}
	self.SetDefaults()
	return &self
}

func (t *GripperCommand_SendGoal_Response) Clone() *GripperCommand_SendGoal_Response {
	c := &GripperCommand_SendGoal_Response{}
	c.Accepted = t.Accepted
	c.Stamp = *t.Stamp.Clone()
	return c
}

func (t *GripperCommand_SendGoal_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GripperCommand_SendGoal_Response) SetDefaults() {
	t.Accepted = false
	t.Stamp.SetDefaults()
}

func (t *GripperCommand_SendGoal_Response) GetTypeSupport() types.MessageTypeSupport {
	return GripperCommand_SendGoal_ResponseTypeSupport
}
func (t *GripperCommand_SendGoal_Response) GetGoalAccepted() bool {
	return t.Accepted
}

// GripperCommand_SendGoal_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GripperCommand_SendGoal_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGripperCommand_SendGoal_ResponsePublisher creates and returns a new publisher for the
// GripperCommand_SendGoal_Response
func NewGripperCommand_SendGoal_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GripperCommand_SendGoal_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GripperCommand_SendGoal_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GripperCommand_SendGoal_ResponsePublisher{pub}, nil
}

func (p *GripperCommand_SendGoal_ResponsePublisher) Publish(msg *GripperCommand_SendGoal_Response) error {
	return p.Publisher.Publish(msg)
}

// GripperCommand_SendGoal_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GripperCommand_SendGoal_ResponseSubscription struct {
	*rclgo.Subscription
}

// GripperCommand_SendGoal_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GripperCommand_SendGoal_ResponseSubscription.
type GripperCommand_SendGoal_ResponseSubscriptionCallback func(msg *GripperCommand_SendGoal_Response, info *rclgo.MessageInfo, err error)

// NewGripperCommand_SendGoal_ResponseSubscription creates and returns a new subscription for the
// GripperCommand_SendGoal_Response
func NewGripperCommand_SendGoal_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GripperCommand_SendGoal_ResponseSubscriptionCallback) (*GripperCommand_SendGoal_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GripperCommand_SendGoal_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GripperCommand_SendGoal_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GripperCommand_SendGoal_ResponseSubscription{sub}, nil
}

func (s *GripperCommand_SendGoal_ResponseSubscription) TakeMessage(out *GripperCommand_SendGoal_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGripperCommand_SendGoal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGripperCommand_SendGoal_ResponseSlice(dst, src []GripperCommand_SendGoal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GripperCommand_SendGoal_ResponseTypeSupport types.MessageTypeSupport = _GripperCommand_SendGoal_ResponseTypeSupport{}

type _GripperCommand_SendGoal_ResponseTypeSupport struct{}

func (t _GripperCommand_SendGoal_ResponseTypeSupport) New() types.Message {
	return NewGripperCommand_SendGoal_Response()
}

func (t _GripperCommand_SendGoal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__GripperCommand_SendGoal_Response
	return (unsafe.Pointer)(C.control_msgs__action__GripperCommand_SendGoal_Response__create())
}

func (t _GripperCommand_SendGoal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__GripperCommand_SendGoal_Response__destroy((*C.control_msgs__action__GripperCommand_SendGoal_Response)(pointer_to_free))
}

func (t _GripperCommand_SendGoal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GripperCommand_SendGoal_Response)
	mem := (*C.control_msgs__action__GripperCommand_SendGoal_Response)(dst)
	mem.accepted = C.bool(m.Accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.stamp), &m.Stamp)
}

func (t _GripperCommand_SendGoal_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GripperCommand_SendGoal_Response)
	mem := (*C.control_msgs__action__GripperCommand_SendGoal_Response)(ros2_message_buffer)
	m.Accepted = bool(mem.accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Stamp, unsafe.Pointer(&mem.stamp))
}

func (t _GripperCommand_SendGoal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__GripperCommand_SendGoal_Response())
}

type CGripperCommand_SendGoal_Response = C.control_msgs__action__GripperCommand_SendGoal_Response
type CGripperCommand_SendGoal_Response__Sequence = C.control_msgs__action__GripperCommand_SendGoal_Response__Sequence

func GripperCommand_SendGoal_Response__Sequence_to_Go(goSlice *[]GripperCommand_SendGoal_Response, cSlice CGripperCommand_SendGoal_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GripperCommand_SendGoal_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GripperCommand_SendGoal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GripperCommand_SendGoal_Response__Sequence_to_C(cSlice *CGripperCommand_SendGoal_Response__Sequence, goSlice []GripperCommand_SendGoal_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__GripperCommand_SendGoal_Response)(C.malloc(C.sizeof_struct_control_msgs__action__GripperCommand_SendGoal_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GripperCommand_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GripperCommand_SendGoal_Response__Array_to_Go(goSlice []GripperCommand_SendGoal_Response, cSlice []CGripperCommand_SendGoal_Response) {
	for i := 0; i < len(cSlice); i++ {
		GripperCommand_SendGoal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GripperCommand_SendGoal_Response__Array_to_C(cSlice []CGripperCommand_SendGoal_Response, goSlice []GripperCommand_SendGoal_Response) {
	for i := 0; i < len(goSlice); i++ {
		GripperCommand_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
