// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <control_msgs/action/joint_trajectory.h>
*/
import "C"

import (
	"context"
	"time"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"

	action_msgs_msg "msgs/action_msgs/msg"
	action_msgs_srv "msgs/action_msgs/srv"
)

func init() {
	typemap.RegisterAction("control_msgs/JointTrajectory", JointTrajectoryTypeSupport)
	typemap.RegisterAction("control_msgs/action/JointTrajectory", JointTrajectoryTypeSupport)
}

type _JointTrajectoryTypeSupport struct {}

func (s _JointTrajectoryTypeSupport) Goal() types.MessageTypeSupport {
	return JointTrajectory_GoalTypeSupport
}

func (s _JointTrajectoryTypeSupport) SendGoal() types.ServiceTypeSupport {
	return JointTrajectory_SendGoalTypeSupport
}

func (s _JointTrajectoryTypeSupport) NewSendGoalResponse(accepted bool, stamp time.Duration) types.Message {
	msg := NewJointTrajectory_SendGoal_Response()
	msg.Accepted = accepted
	secs := stamp.Truncate(time.Second)
	msg.Stamp.Sec = int32(secs)
	msg.Stamp.Nanosec = uint32(stamp - secs)
	return msg
}

func (s _JointTrajectoryTypeSupport) Result() types.MessageTypeSupport {
	return JointTrajectory_ResultTypeSupport
}

func (s _JointTrajectoryTypeSupport) GetResult() types.ServiceTypeSupport {
	return JointTrajectory_GetResultTypeSupport
}

func (s _JointTrajectoryTypeSupport) NewGetResultResponse(status int8, result types.Message) types.Message {
	msg := NewJointTrajectory_GetResult_Response()
	msg.Status = status
	if result == nil {
		msg.Result = *NewJointTrajectory_Result()
	} else {
		msg.Result = *result.(*JointTrajectory_Result)
	}
	return msg
}

func (s _JointTrajectoryTypeSupport) CancelGoal() types.ServiceTypeSupport {
	return action_msgs_srv.CancelGoalTypeSupport
}

func (s _JointTrajectoryTypeSupport) Feedback() types.MessageTypeSupport {
	return JointTrajectory_FeedbackTypeSupport
}

func (s _JointTrajectoryTypeSupport) FeedbackMessage() types.MessageTypeSupport {
	return JointTrajectory_FeedbackMessageTypeSupport
}

func (s _JointTrajectoryTypeSupport) NewFeedbackMessage(goalID *types.GoalID, feedback types.Message) types.Message {
	msg := NewJointTrajectory_FeedbackMessage()
	msg.GoalID.Uuid = *goalID
	msg.Feedback = *feedback.(*JointTrajectory_Feedback)
	return msg
}

func (s _JointTrajectoryTypeSupport) GoalStatusArray() types.MessageTypeSupport {
	return action_msgs_msg.GoalStatusArrayTypeSupport
}

func (s _JointTrajectoryTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_action_type_support_handle__control_msgs__action__JointTrajectory())
}

// Modifying this variable is undefined behavior.
var JointTrajectoryTypeSupport types.ActionTypeSupport = _JointTrajectoryTypeSupport{}

type JointTrajectoryFeedbackSender struct {
	sender rclgo.FeedbackSender
}

func (s *JointTrajectoryFeedbackSender) Send(msg *JointTrajectory_Feedback) error {
	return s.sender.Send(msg)
}

type JointTrajectoryGoalHandle struct{
	*rclgo.GoalHandle

	Description *JointTrajectory_Goal
}

func (g *JointTrajectoryGoalHandle) Accept() (*JointTrajectoryFeedbackSender, error) {
	s, err := g.GoalHandle.Accept()
	if err != nil {
		return nil, err
	}
	return &JointTrajectoryFeedbackSender{*s}, nil
}

type JointTrajectoryAction interface {
	ExecuteGoal(context.Context, *JointTrajectoryGoalHandle) (*JointTrajectory_Result, error)
}

func NewJointTrajectoryAction(
	executeGoal func(context.Context, *JointTrajectoryGoalHandle) (*JointTrajectory_Result, error),
) JointTrajectoryAction {
	return _JointTrajectoryFuncAction(executeGoal)
}

type _JointTrajectoryFuncAction func(context.Context, *JointTrajectoryGoalHandle) (*JointTrajectory_Result, error)

func (a _JointTrajectoryFuncAction) ExecuteGoal(
	ctx context.Context, goal *JointTrajectoryGoalHandle,
) (*JointTrajectory_Result, error) {
	return a(ctx, goal)
}

type _JointTrajectoryAction struct {
	action JointTrajectoryAction
}

func (a _JointTrajectoryAction) ExecuteGoal(ctx context.Context, handle *rclgo.GoalHandle) (types.Message, error) {
	return a.action.ExecuteGoal(ctx, &JointTrajectoryGoalHandle{
		GoalHandle:  handle,
		Description: handle.Description.(*JointTrajectory_Goal),
	})
}

func (a _JointTrajectoryAction) TypeSupport() types.ActionTypeSupport {
	return JointTrajectoryTypeSupport
}

type JointTrajectoryServer struct{
	*rclgo.ActionServer
}

func NewJointTrajectoryServer(node *rclgo.Node, name string, action JointTrajectoryAction, opts *rclgo.ActionServerOptions) (*JointTrajectoryServer, error) {
	server, err := node.NewActionServer(name, _JointTrajectoryAction{action}, opts)
	if err != nil {
		return nil, err
	}
	return &JointTrajectoryServer{server}, nil
}

type JointTrajectoryFeedbackHandler func(context.Context, *JointTrajectory_FeedbackMessage)

type JointTrajectoryStatusHandler func(context.Context, *action_msgs_msg.GoalStatus)

type JointTrajectoryClient struct{
	*rclgo.ActionClient
}

func NewJointTrajectoryClient(node *rclgo.Node, name string, opts *rclgo.ActionClientOptions) (*JointTrajectoryClient, error) {
	client, err := node.NewActionClient(name, JointTrajectoryTypeSupport, opts)
	if err != nil {
		return nil, err
	}
	return &JointTrajectoryClient{client}, nil
}

func (c *JointTrajectoryClient) WatchGoal(ctx context.Context, goal *JointTrajectory_Goal, onFeedback JointTrajectoryFeedbackHandler) (*JointTrajectory_GetResult_Response, *types.GoalID, error) {
	var resp types.Message
	var goalID *types.GoalID
	var err error
	if onFeedback == nil {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, nil)
	} else {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, func(ctx context.Context, msg types.Message) {
			onFeedback(ctx, msg.(*JointTrajectory_FeedbackMessage))
		})
	}
	if r, ok := resp.(*JointTrajectory_GetResult_Response); ok {
		return r, goalID, err
	}
	return nil, goalID, err
}

func (c *JointTrajectoryClient) SendGoal(ctx context.Context, goal *JointTrajectory_Goal) (*JointTrajectory_SendGoal_Response, *types.GoalID, error) {
	resp, id, err := c.ActionClient.SendGoal(ctx, goal)
	if r, ok := resp.(*JointTrajectory_SendGoal_Response); ok {
		return r, id, err
	}
	return nil, id, err
}

func (c *JointTrajectoryClient) SendGoalRequest(ctx context.Context, request *JointTrajectory_SendGoal_Request) (*JointTrajectory_SendGoal_Response, error) {
	resp, err := c.ActionClient.SendGoalRequest(ctx, request)
	if r, ok := resp.(*JointTrajectory_SendGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *JointTrajectoryClient) GetResult(ctx context.Context, goalID *types.GoalID) (*JointTrajectory_GetResult_Response, error) {
	resp, err := c.ActionClient.GetResult(ctx, goalID)
	if r, ok := resp.(*JointTrajectory_GetResult_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *JointTrajectoryClient) CancelGoal(ctx context.Context, request *action_msgs_srv.CancelGoal_Request) (*action_msgs_srv.CancelGoal_Response, error) {
	resp, err := c.ActionClient.CancelGoal(ctx, request)
	if r, ok := resp.(*action_msgs_srv.CancelGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *JointTrajectoryClient) WatchFeedback(ctx context.Context, goalID *types.GoalID, handler JointTrajectoryFeedbackHandler) <-chan error {
	return c.ActionClient.WatchFeedback(ctx, goalID, func(ctx context.Context, msg types.Message) {
		handler(ctx, msg.(*JointTrajectory_FeedbackMessage))
	})
}

func (c *JointTrajectoryClient) WatchStatus(ctx context.Context, goalID *types.GoalID, handler JointTrajectoryStatusHandler) <-chan error {
	return c.ActionClient.WatchStatus(ctx, goalID, func(ctx context.Context, msg types.Message) {
		handler(ctx, msg.(*action_msgs_msg.GoalStatus))
	})
}
