// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/joint_trajectory.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/JointTrajectory_FeedbackMessage", JointTrajectory_FeedbackMessageTypeSupport)
	typemap.RegisterMessage("control_msgs/action/JointTrajectory_FeedbackMessage", JointTrajectory_FeedbackMessageTypeSupport)
}

type JointTrajectory_FeedbackMessage struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Feedback JointTrajectory_Feedback `yaml:"feedback"`
}

// NewJointTrajectory_FeedbackMessage creates a new JointTrajectory_FeedbackMessage with default values.
func NewJointTrajectory_FeedbackMessage() *JointTrajectory_FeedbackMessage {
	self := JointTrajectory_FeedbackMessage{}
	self.SetDefaults()
	return &self
}

func (t *JointTrajectory_FeedbackMessage) Clone() *JointTrajectory_FeedbackMessage {
	c := &JointTrajectory_FeedbackMessage{}
	c.GoalID = *t.GoalID.Clone()
	c.Feedback = *t.Feedback.Clone()
	return c
}

func (t *JointTrajectory_FeedbackMessage) CloneMsg() types.Message {
	return t.Clone()
}

func (t *JointTrajectory_FeedbackMessage) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Feedback.SetDefaults()
}

func (t *JointTrajectory_FeedbackMessage) GetTypeSupport() types.MessageTypeSupport {
	return JointTrajectory_FeedbackMessageTypeSupport
}
func (t *JointTrajectory_FeedbackMessage) GetGoalID() *types.GoalID {
	return (*types.GoalID)(&t.GoalID.Uuid)
}

func (t *JointTrajectory_FeedbackMessage) SetGoalID(id *types.GoalID) {
	t.GoalID.Uuid = *id
}

// JointTrajectory_FeedbackMessagePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type JointTrajectory_FeedbackMessagePublisher struct {
	*rclgo.Publisher
}

// NewJointTrajectory_FeedbackMessagePublisher creates and returns a new publisher for the
// JointTrajectory_FeedbackMessage
func NewJointTrajectory_FeedbackMessagePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*JointTrajectory_FeedbackMessagePublisher, error) {
	pub, err := node.NewPublisher(topic_name, JointTrajectory_FeedbackMessageTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &JointTrajectory_FeedbackMessagePublisher{pub}, nil
}

func (p *JointTrajectory_FeedbackMessagePublisher) Publish(msg *JointTrajectory_FeedbackMessage) error {
	return p.Publisher.Publish(msg)
}

// JointTrajectory_FeedbackMessageSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type JointTrajectory_FeedbackMessageSubscription struct {
	*rclgo.Subscription
}

// JointTrajectory_FeedbackMessageSubscriptionCallback type is used to provide a subscription
// handler function for a JointTrajectory_FeedbackMessageSubscription.
type JointTrajectory_FeedbackMessageSubscriptionCallback func(msg *JointTrajectory_FeedbackMessage, info *rclgo.MessageInfo, err error)

// NewJointTrajectory_FeedbackMessageSubscription creates and returns a new subscription for the
// JointTrajectory_FeedbackMessage
func NewJointTrajectory_FeedbackMessageSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback JointTrajectory_FeedbackMessageSubscriptionCallback) (*JointTrajectory_FeedbackMessageSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg JointTrajectory_FeedbackMessage
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, JointTrajectory_FeedbackMessageTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &JointTrajectory_FeedbackMessageSubscription{sub}, nil
}

func (s *JointTrajectory_FeedbackMessageSubscription) TakeMessage(out *JointTrajectory_FeedbackMessage) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneJointTrajectory_FeedbackMessageSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneJointTrajectory_FeedbackMessageSlice(dst, src []JointTrajectory_FeedbackMessage) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var JointTrajectory_FeedbackMessageTypeSupport types.MessageTypeSupport = _JointTrajectory_FeedbackMessageTypeSupport{}

type _JointTrajectory_FeedbackMessageTypeSupport struct{}

func (t _JointTrajectory_FeedbackMessageTypeSupport) New() types.Message {
	return NewJointTrajectory_FeedbackMessage()
}

func (t _JointTrajectory_FeedbackMessageTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__JointTrajectory_FeedbackMessage
	return (unsafe.Pointer)(C.control_msgs__action__JointTrajectory_FeedbackMessage__create())
}

func (t _JointTrajectory_FeedbackMessageTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__JointTrajectory_FeedbackMessage__destroy((*C.control_msgs__action__JointTrajectory_FeedbackMessage)(pointer_to_free))
}

func (t _JointTrajectory_FeedbackMessageTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*JointTrajectory_FeedbackMessage)
	mem := (*C.control_msgs__action__JointTrajectory_FeedbackMessage)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	JointTrajectory_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&mem.feedback), &m.Feedback)
}

func (t _JointTrajectory_FeedbackMessageTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*JointTrajectory_FeedbackMessage)
	mem := (*C.control_msgs__action__JointTrajectory_FeedbackMessage)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	JointTrajectory_FeedbackTypeSupport.AsGoStruct(&m.Feedback, unsafe.Pointer(&mem.feedback))
}

func (t _JointTrajectory_FeedbackMessageTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__JointTrajectory_FeedbackMessage())
}

type CJointTrajectory_FeedbackMessage = C.control_msgs__action__JointTrajectory_FeedbackMessage
type CJointTrajectory_FeedbackMessage__Sequence = C.control_msgs__action__JointTrajectory_FeedbackMessage__Sequence

func JointTrajectory_FeedbackMessage__Sequence_to_Go(goSlice *[]JointTrajectory_FeedbackMessage, cSlice CJointTrajectory_FeedbackMessage__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]JointTrajectory_FeedbackMessage, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		JointTrajectory_FeedbackMessageTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func JointTrajectory_FeedbackMessage__Sequence_to_C(cSlice *CJointTrajectory_FeedbackMessage__Sequence, goSlice []JointTrajectory_FeedbackMessage) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__JointTrajectory_FeedbackMessage)(C.malloc(C.sizeof_struct_control_msgs__action__JointTrajectory_FeedbackMessage * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		JointTrajectory_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func JointTrajectory_FeedbackMessage__Array_to_Go(goSlice []JointTrajectory_FeedbackMessage, cSlice []CJointTrajectory_FeedbackMessage) {
	for i := 0; i < len(cSlice); i++ {
		JointTrajectory_FeedbackMessageTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func JointTrajectory_FeedbackMessage__Array_to_C(cSlice []CJointTrajectory_FeedbackMessage, goSlice []JointTrajectory_FeedbackMessage) {
	for i := 0; i < len(goSlice); i++ {
		JointTrajectory_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
