// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/joint_trajectory.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/JointTrajectory_Feedback", JointTrajectory_FeedbackTypeSupport)
	typemap.RegisterMessage("control_msgs/action/JointTrajectory_Feedback", JointTrajectory_FeedbackTypeSupport)
}

type JointTrajectory_Feedback struct {
}

// NewJointTrajectory_Feedback creates a new JointTrajectory_Feedback with default values.
func NewJointTrajectory_Feedback() *JointTrajectory_Feedback {
	self := JointTrajectory_Feedback{}
	self.SetDefaults()
	return &self
}

func (t *JointTrajectory_Feedback) Clone() *JointTrajectory_Feedback {
	c := &JointTrajectory_Feedback{}
	return c
}

func (t *JointTrajectory_Feedback) CloneMsg() types.Message {
	return t.Clone()
}

func (t *JointTrajectory_Feedback) SetDefaults() {
}

func (t *JointTrajectory_Feedback) GetTypeSupport() types.MessageTypeSupport {
	return JointTrajectory_FeedbackTypeSupport
}

// JointTrajectory_FeedbackPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type JointTrajectory_FeedbackPublisher struct {
	*rclgo.Publisher
}

// NewJointTrajectory_FeedbackPublisher creates and returns a new publisher for the
// JointTrajectory_Feedback
func NewJointTrajectory_FeedbackPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*JointTrajectory_FeedbackPublisher, error) {
	pub, err := node.NewPublisher(topic_name, JointTrajectory_FeedbackTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &JointTrajectory_FeedbackPublisher{pub}, nil
}

func (p *JointTrajectory_FeedbackPublisher) Publish(msg *JointTrajectory_Feedback) error {
	return p.Publisher.Publish(msg)
}

// JointTrajectory_FeedbackSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type JointTrajectory_FeedbackSubscription struct {
	*rclgo.Subscription
}

// JointTrajectory_FeedbackSubscriptionCallback type is used to provide a subscription
// handler function for a JointTrajectory_FeedbackSubscription.
type JointTrajectory_FeedbackSubscriptionCallback func(msg *JointTrajectory_Feedback, info *rclgo.MessageInfo, err error)

// NewJointTrajectory_FeedbackSubscription creates and returns a new subscription for the
// JointTrajectory_Feedback
func NewJointTrajectory_FeedbackSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback JointTrajectory_FeedbackSubscriptionCallback) (*JointTrajectory_FeedbackSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg JointTrajectory_Feedback
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, JointTrajectory_FeedbackTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &JointTrajectory_FeedbackSubscription{sub}, nil
}

func (s *JointTrajectory_FeedbackSubscription) TakeMessage(out *JointTrajectory_Feedback) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneJointTrajectory_FeedbackSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneJointTrajectory_FeedbackSlice(dst, src []JointTrajectory_Feedback) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var JointTrajectory_FeedbackTypeSupport types.MessageTypeSupport = _JointTrajectory_FeedbackTypeSupport{}

type _JointTrajectory_FeedbackTypeSupport struct{}

func (t _JointTrajectory_FeedbackTypeSupport) New() types.Message {
	return NewJointTrajectory_Feedback()
}

func (t _JointTrajectory_FeedbackTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__JointTrajectory_Feedback
	return (unsafe.Pointer)(C.control_msgs__action__JointTrajectory_Feedback__create())
}

func (t _JointTrajectory_FeedbackTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__JointTrajectory_Feedback__destroy((*C.control_msgs__action__JointTrajectory_Feedback)(pointer_to_free))
}

func (t _JointTrajectory_FeedbackTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _JointTrajectory_FeedbackTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _JointTrajectory_FeedbackTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__JointTrajectory_Feedback())
}

type CJointTrajectory_Feedback = C.control_msgs__action__JointTrajectory_Feedback
type CJointTrajectory_Feedback__Sequence = C.control_msgs__action__JointTrajectory_Feedback__Sequence

func JointTrajectory_Feedback__Sequence_to_Go(goSlice *[]JointTrajectory_Feedback, cSlice CJointTrajectory_Feedback__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]JointTrajectory_Feedback, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		JointTrajectory_FeedbackTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func JointTrajectory_Feedback__Sequence_to_C(cSlice *CJointTrajectory_Feedback__Sequence, goSlice []JointTrajectory_Feedback) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__JointTrajectory_Feedback)(C.malloc(C.sizeof_struct_control_msgs__action__JointTrajectory_Feedback * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		JointTrajectory_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func JointTrajectory_Feedback__Array_to_Go(goSlice []JointTrajectory_Feedback, cSlice []CJointTrajectory_Feedback) {
	for i := 0; i < len(cSlice); i++ {
		JointTrajectory_FeedbackTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func JointTrajectory_Feedback__Array_to_C(cSlice []CJointTrajectory_Feedback, goSlice []JointTrajectory_Feedback) {
	for i := 0; i < len(goSlice); i++ {
		JointTrajectory_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
