// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/parallel_gripper_command.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/ParallelGripperCommand_GetResult_Response", ParallelGripperCommand_GetResult_ResponseTypeSupport)
	typemap.RegisterMessage("control_msgs/action/ParallelGripperCommand_GetResult_Response", ParallelGripperCommand_GetResult_ResponseTypeSupport)
}

type ParallelGripperCommand_GetResult_Response struct {
	Status int8 `yaml:"status"`
	Result ParallelGripperCommand_Result `yaml:"result"`
}

// NewParallelGripperCommand_GetResult_Response creates a new ParallelGripperCommand_GetResult_Response with default values.
func NewParallelGripperCommand_GetResult_Response() *ParallelGripperCommand_GetResult_Response {
	self := ParallelGripperCommand_GetResult_Response{}
	self.SetDefaults()
	return &self
}

func (t *ParallelGripperCommand_GetResult_Response) Clone() *ParallelGripperCommand_GetResult_Response {
	c := &ParallelGripperCommand_GetResult_Response{}
	c.Status = t.Status
	c.Result = *t.Result.Clone()
	return c
}

func (t *ParallelGripperCommand_GetResult_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ParallelGripperCommand_GetResult_Response) SetDefaults() {
	t.Status = 0
	t.Result.SetDefaults()
}

func (t *ParallelGripperCommand_GetResult_Response) GetTypeSupport() types.MessageTypeSupport {
	return ParallelGripperCommand_GetResult_ResponseTypeSupport
}

// ParallelGripperCommand_GetResult_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ParallelGripperCommand_GetResult_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewParallelGripperCommand_GetResult_ResponsePublisher creates and returns a new publisher for the
// ParallelGripperCommand_GetResult_Response
func NewParallelGripperCommand_GetResult_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ParallelGripperCommand_GetResult_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ParallelGripperCommand_GetResult_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ParallelGripperCommand_GetResult_ResponsePublisher{pub}, nil
}

func (p *ParallelGripperCommand_GetResult_ResponsePublisher) Publish(msg *ParallelGripperCommand_GetResult_Response) error {
	return p.Publisher.Publish(msg)
}

// ParallelGripperCommand_GetResult_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ParallelGripperCommand_GetResult_ResponseSubscription struct {
	*rclgo.Subscription
}

// ParallelGripperCommand_GetResult_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ParallelGripperCommand_GetResult_ResponseSubscription.
type ParallelGripperCommand_GetResult_ResponseSubscriptionCallback func(msg *ParallelGripperCommand_GetResult_Response, info *rclgo.MessageInfo, err error)

// NewParallelGripperCommand_GetResult_ResponseSubscription creates and returns a new subscription for the
// ParallelGripperCommand_GetResult_Response
func NewParallelGripperCommand_GetResult_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ParallelGripperCommand_GetResult_ResponseSubscriptionCallback) (*ParallelGripperCommand_GetResult_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ParallelGripperCommand_GetResult_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ParallelGripperCommand_GetResult_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ParallelGripperCommand_GetResult_ResponseSubscription{sub}, nil
}

func (s *ParallelGripperCommand_GetResult_ResponseSubscription) TakeMessage(out *ParallelGripperCommand_GetResult_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneParallelGripperCommand_GetResult_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneParallelGripperCommand_GetResult_ResponseSlice(dst, src []ParallelGripperCommand_GetResult_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ParallelGripperCommand_GetResult_ResponseTypeSupport types.MessageTypeSupport = _ParallelGripperCommand_GetResult_ResponseTypeSupport{}

type _ParallelGripperCommand_GetResult_ResponseTypeSupport struct{}

func (t _ParallelGripperCommand_GetResult_ResponseTypeSupport) New() types.Message {
	return NewParallelGripperCommand_GetResult_Response()
}

func (t _ParallelGripperCommand_GetResult_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__ParallelGripperCommand_GetResult_Response
	return (unsafe.Pointer)(C.control_msgs__action__ParallelGripperCommand_GetResult_Response__create())
}

func (t _ParallelGripperCommand_GetResult_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__ParallelGripperCommand_GetResult_Response__destroy((*C.control_msgs__action__ParallelGripperCommand_GetResult_Response)(pointer_to_free))
}

func (t _ParallelGripperCommand_GetResult_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ParallelGripperCommand_GetResult_Response)
	mem := (*C.control_msgs__action__ParallelGripperCommand_GetResult_Response)(dst)
	mem.status = C.int8_t(m.Status)
	ParallelGripperCommand_ResultTypeSupport.AsCStruct(unsafe.Pointer(&mem.result), &m.Result)
}

func (t _ParallelGripperCommand_GetResult_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ParallelGripperCommand_GetResult_Response)
	mem := (*C.control_msgs__action__ParallelGripperCommand_GetResult_Response)(ros2_message_buffer)
	m.Status = int8(mem.status)
	ParallelGripperCommand_ResultTypeSupport.AsGoStruct(&m.Result, unsafe.Pointer(&mem.result))
}

func (t _ParallelGripperCommand_GetResult_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__ParallelGripperCommand_GetResult_Response())
}

type CParallelGripperCommand_GetResult_Response = C.control_msgs__action__ParallelGripperCommand_GetResult_Response
type CParallelGripperCommand_GetResult_Response__Sequence = C.control_msgs__action__ParallelGripperCommand_GetResult_Response__Sequence

func ParallelGripperCommand_GetResult_Response__Sequence_to_Go(goSlice *[]ParallelGripperCommand_GetResult_Response, cSlice CParallelGripperCommand_GetResult_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ParallelGripperCommand_GetResult_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ParallelGripperCommand_GetResult_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ParallelGripperCommand_GetResult_Response__Sequence_to_C(cSlice *CParallelGripperCommand_GetResult_Response__Sequence, goSlice []ParallelGripperCommand_GetResult_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__ParallelGripperCommand_GetResult_Response)(C.malloc(C.sizeof_struct_control_msgs__action__ParallelGripperCommand_GetResult_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ParallelGripperCommand_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ParallelGripperCommand_GetResult_Response__Array_to_Go(goSlice []ParallelGripperCommand_GetResult_Response, cSlice []CParallelGripperCommand_GetResult_Response) {
	for i := 0; i < len(cSlice); i++ {
		ParallelGripperCommand_GetResult_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ParallelGripperCommand_GetResult_Response__Array_to_C(cSlice []CParallelGripperCommand_GetResult_Response, goSlice []ParallelGripperCommand_GetResult_Response) {
	for i := 0; i < len(goSlice); i++ {
		ParallelGripperCommand_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
