// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/parallel_gripper_command.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/ParallelGripperCommand_FeedbackMessage", ParallelGripperCommand_FeedbackMessageTypeSupport)
	typemap.RegisterMessage("control_msgs/action/ParallelGripperCommand_FeedbackMessage", ParallelGripperCommand_FeedbackMessageTypeSupport)
}

type ParallelGripperCommand_FeedbackMessage struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Feedback ParallelGripperCommand_Feedback `yaml:"feedback"`
}

// NewParallelGripperCommand_FeedbackMessage creates a new ParallelGripperCommand_FeedbackMessage with default values.
func NewParallelGripperCommand_FeedbackMessage() *ParallelGripperCommand_FeedbackMessage {
	self := ParallelGripperCommand_FeedbackMessage{}
	self.SetDefaults()
	return &self
}

func (t *ParallelGripperCommand_FeedbackMessage) Clone() *ParallelGripperCommand_FeedbackMessage {
	c := &ParallelGripperCommand_FeedbackMessage{}
	c.GoalID = *t.GoalID.Clone()
	c.Feedback = *t.Feedback.Clone()
	return c
}

func (t *ParallelGripperCommand_FeedbackMessage) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ParallelGripperCommand_FeedbackMessage) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Feedback.SetDefaults()
}

func (t *ParallelGripperCommand_FeedbackMessage) GetTypeSupport() types.MessageTypeSupport {
	return ParallelGripperCommand_FeedbackMessageTypeSupport
}
func (t *ParallelGripperCommand_FeedbackMessage) GetGoalID() *types.GoalID {
	return (*types.GoalID)(&t.GoalID.Uuid)
}

func (t *ParallelGripperCommand_FeedbackMessage) SetGoalID(id *types.GoalID) {
	t.GoalID.Uuid = *id
}

// ParallelGripperCommand_FeedbackMessagePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ParallelGripperCommand_FeedbackMessagePublisher struct {
	*rclgo.Publisher
}

// NewParallelGripperCommand_FeedbackMessagePublisher creates and returns a new publisher for the
// ParallelGripperCommand_FeedbackMessage
func NewParallelGripperCommand_FeedbackMessagePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ParallelGripperCommand_FeedbackMessagePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ParallelGripperCommand_FeedbackMessageTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ParallelGripperCommand_FeedbackMessagePublisher{pub}, nil
}

func (p *ParallelGripperCommand_FeedbackMessagePublisher) Publish(msg *ParallelGripperCommand_FeedbackMessage) error {
	return p.Publisher.Publish(msg)
}

// ParallelGripperCommand_FeedbackMessageSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ParallelGripperCommand_FeedbackMessageSubscription struct {
	*rclgo.Subscription
}

// ParallelGripperCommand_FeedbackMessageSubscriptionCallback type is used to provide a subscription
// handler function for a ParallelGripperCommand_FeedbackMessageSubscription.
type ParallelGripperCommand_FeedbackMessageSubscriptionCallback func(msg *ParallelGripperCommand_FeedbackMessage, info *rclgo.MessageInfo, err error)

// NewParallelGripperCommand_FeedbackMessageSubscription creates and returns a new subscription for the
// ParallelGripperCommand_FeedbackMessage
func NewParallelGripperCommand_FeedbackMessageSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ParallelGripperCommand_FeedbackMessageSubscriptionCallback) (*ParallelGripperCommand_FeedbackMessageSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ParallelGripperCommand_FeedbackMessage
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ParallelGripperCommand_FeedbackMessageTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ParallelGripperCommand_FeedbackMessageSubscription{sub}, nil
}

func (s *ParallelGripperCommand_FeedbackMessageSubscription) TakeMessage(out *ParallelGripperCommand_FeedbackMessage) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneParallelGripperCommand_FeedbackMessageSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneParallelGripperCommand_FeedbackMessageSlice(dst, src []ParallelGripperCommand_FeedbackMessage) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ParallelGripperCommand_FeedbackMessageTypeSupport types.MessageTypeSupport = _ParallelGripperCommand_FeedbackMessageTypeSupport{}

type _ParallelGripperCommand_FeedbackMessageTypeSupport struct{}

func (t _ParallelGripperCommand_FeedbackMessageTypeSupport) New() types.Message {
	return NewParallelGripperCommand_FeedbackMessage()
}

func (t _ParallelGripperCommand_FeedbackMessageTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__ParallelGripperCommand_FeedbackMessage
	return (unsafe.Pointer)(C.control_msgs__action__ParallelGripperCommand_FeedbackMessage__create())
}

func (t _ParallelGripperCommand_FeedbackMessageTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__ParallelGripperCommand_FeedbackMessage__destroy((*C.control_msgs__action__ParallelGripperCommand_FeedbackMessage)(pointer_to_free))
}

func (t _ParallelGripperCommand_FeedbackMessageTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ParallelGripperCommand_FeedbackMessage)
	mem := (*C.control_msgs__action__ParallelGripperCommand_FeedbackMessage)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	ParallelGripperCommand_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&mem.feedback), &m.Feedback)
}

func (t _ParallelGripperCommand_FeedbackMessageTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ParallelGripperCommand_FeedbackMessage)
	mem := (*C.control_msgs__action__ParallelGripperCommand_FeedbackMessage)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	ParallelGripperCommand_FeedbackTypeSupport.AsGoStruct(&m.Feedback, unsafe.Pointer(&mem.feedback))
}

func (t _ParallelGripperCommand_FeedbackMessageTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__ParallelGripperCommand_FeedbackMessage())
}

type CParallelGripperCommand_FeedbackMessage = C.control_msgs__action__ParallelGripperCommand_FeedbackMessage
type CParallelGripperCommand_FeedbackMessage__Sequence = C.control_msgs__action__ParallelGripperCommand_FeedbackMessage__Sequence

func ParallelGripperCommand_FeedbackMessage__Sequence_to_Go(goSlice *[]ParallelGripperCommand_FeedbackMessage, cSlice CParallelGripperCommand_FeedbackMessage__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ParallelGripperCommand_FeedbackMessage, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ParallelGripperCommand_FeedbackMessageTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ParallelGripperCommand_FeedbackMessage__Sequence_to_C(cSlice *CParallelGripperCommand_FeedbackMessage__Sequence, goSlice []ParallelGripperCommand_FeedbackMessage) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__ParallelGripperCommand_FeedbackMessage)(C.malloc(C.sizeof_struct_control_msgs__action__ParallelGripperCommand_FeedbackMessage * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ParallelGripperCommand_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ParallelGripperCommand_FeedbackMessage__Array_to_Go(goSlice []ParallelGripperCommand_FeedbackMessage, cSlice []CParallelGripperCommand_FeedbackMessage) {
	for i := 0; i < len(cSlice); i++ {
		ParallelGripperCommand_FeedbackMessageTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ParallelGripperCommand_FeedbackMessage__Array_to_C(cSlice []CParallelGripperCommand_FeedbackMessage, goSlice []ParallelGripperCommand_FeedbackMessage) {
	for i := 0; i < len(goSlice); i++ {
		ParallelGripperCommand_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
