// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/point_head.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/PointHead_SendGoal_Response", PointHead_SendGoal_ResponseTypeSupport)
	typemap.RegisterMessage("control_msgs/action/PointHead_SendGoal_Response", PointHead_SendGoal_ResponseTypeSupport)
}

type PointHead_SendGoal_Response struct {
	Accepted bool `yaml:"accepted"`
	Stamp builtin_interfaces_msg.Time `yaml:"stamp"`
}

// NewPointHead_SendGoal_Response creates a new PointHead_SendGoal_Response with default values.
func NewPointHead_SendGoal_Response() *PointHead_SendGoal_Response {
	self := PointHead_SendGoal_Response{}
	self.SetDefaults()
	return &self
}

func (t *PointHead_SendGoal_Response) Clone() *PointHead_SendGoal_Response {
	c := &PointHead_SendGoal_Response{}
	c.Accepted = t.Accepted
	c.Stamp = *t.Stamp.Clone()
	return c
}

func (t *PointHead_SendGoal_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *PointHead_SendGoal_Response) SetDefaults() {
	t.Accepted = false
	t.Stamp.SetDefaults()
}

func (t *PointHead_SendGoal_Response) GetTypeSupport() types.MessageTypeSupport {
	return PointHead_SendGoal_ResponseTypeSupport
}
func (t *PointHead_SendGoal_Response) GetGoalAccepted() bool {
	return t.Accepted
}

// PointHead_SendGoal_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type PointHead_SendGoal_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewPointHead_SendGoal_ResponsePublisher creates and returns a new publisher for the
// PointHead_SendGoal_Response
func NewPointHead_SendGoal_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*PointHead_SendGoal_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, PointHead_SendGoal_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PointHead_SendGoal_ResponsePublisher{pub}, nil
}

func (p *PointHead_SendGoal_ResponsePublisher) Publish(msg *PointHead_SendGoal_Response) error {
	return p.Publisher.Publish(msg)
}

// PointHead_SendGoal_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type PointHead_SendGoal_ResponseSubscription struct {
	*rclgo.Subscription
}

// PointHead_SendGoal_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a PointHead_SendGoal_ResponseSubscription.
type PointHead_SendGoal_ResponseSubscriptionCallback func(msg *PointHead_SendGoal_Response, info *rclgo.MessageInfo, err error)

// NewPointHead_SendGoal_ResponseSubscription creates and returns a new subscription for the
// PointHead_SendGoal_Response
func NewPointHead_SendGoal_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback PointHead_SendGoal_ResponseSubscriptionCallback) (*PointHead_SendGoal_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg PointHead_SendGoal_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, PointHead_SendGoal_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &PointHead_SendGoal_ResponseSubscription{sub}, nil
}

func (s *PointHead_SendGoal_ResponseSubscription) TakeMessage(out *PointHead_SendGoal_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// ClonePointHead_SendGoal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePointHead_SendGoal_ResponseSlice(dst, src []PointHead_SendGoal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var PointHead_SendGoal_ResponseTypeSupport types.MessageTypeSupport = _PointHead_SendGoal_ResponseTypeSupport{}

type _PointHead_SendGoal_ResponseTypeSupport struct{}

func (t _PointHead_SendGoal_ResponseTypeSupport) New() types.Message {
	return NewPointHead_SendGoal_Response()
}

func (t _PointHead_SendGoal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__PointHead_SendGoal_Response
	return (unsafe.Pointer)(C.control_msgs__action__PointHead_SendGoal_Response__create())
}

func (t _PointHead_SendGoal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__PointHead_SendGoal_Response__destroy((*C.control_msgs__action__PointHead_SendGoal_Response)(pointer_to_free))
}

func (t _PointHead_SendGoal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*PointHead_SendGoal_Response)
	mem := (*C.control_msgs__action__PointHead_SendGoal_Response)(dst)
	mem.accepted = C.bool(m.Accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.stamp), &m.Stamp)
}

func (t _PointHead_SendGoal_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*PointHead_SendGoal_Response)
	mem := (*C.control_msgs__action__PointHead_SendGoal_Response)(ros2_message_buffer)
	m.Accepted = bool(mem.accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Stamp, unsafe.Pointer(&mem.stamp))
}

func (t _PointHead_SendGoal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__PointHead_SendGoal_Response())
}

type CPointHead_SendGoal_Response = C.control_msgs__action__PointHead_SendGoal_Response
type CPointHead_SendGoal_Response__Sequence = C.control_msgs__action__PointHead_SendGoal_Response__Sequence

func PointHead_SendGoal_Response__Sequence_to_Go(goSlice *[]PointHead_SendGoal_Response, cSlice CPointHead_SendGoal_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]PointHead_SendGoal_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		PointHead_SendGoal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func PointHead_SendGoal_Response__Sequence_to_C(cSlice *CPointHead_SendGoal_Response__Sequence, goSlice []PointHead_SendGoal_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__PointHead_SendGoal_Response)(C.malloc(C.sizeof_struct_control_msgs__action__PointHead_SendGoal_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		PointHead_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func PointHead_SendGoal_Response__Array_to_Go(goSlice []PointHead_SendGoal_Response, cSlice []CPointHead_SendGoal_Response) {
	for i := 0; i < len(cSlice); i++ {
		PointHead_SendGoal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func PointHead_SendGoal_Response__Array_to_C(cSlice []CPointHead_SendGoal_Response, goSlice []PointHead_SendGoal_Response) {
	for i := 0; i < len(goSlice); i++ {
		PointHead_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
