// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <control_msgs/action/single_joint_position.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("control_msgs/SingleJointPosition_SendGoal", SingleJointPosition_SendGoalTypeSupport)
	typemap.RegisterService("control_msgs/action/SingleJointPosition_SendGoal", SingleJointPosition_SendGoalTypeSupport)
}

type _SingleJointPosition_SendGoalTypeSupport struct {}

func (s _SingleJointPosition_SendGoalTypeSupport) Request() types.MessageTypeSupport {
	return SingleJointPosition_SendGoal_RequestTypeSupport
}

func (s _SingleJointPosition_SendGoalTypeSupport) Response() types.MessageTypeSupport {
	return SingleJointPosition_SendGoal_ResponseTypeSupport
}

func (s _SingleJointPosition_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__control_msgs__action__SingleJointPosition_SendGoal())
}

// Modifying this variable is undefined behavior.
var SingleJointPosition_SendGoalTypeSupport types.ServiceTypeSupport = _SingleJointPosition_SendGoalTypeSupport{}

// SingleJointPosition_SendGoalClient wraps rclgo.Client to provide type safe helper
// functions
type SingleJointPosition_SendGoalClient struct {
	*rclgo.Client
}

// NewSingleJointPosition_SendGoalClient creates and returns a new client for the
// SingleJointPosition_SendGoal
func NewSingleJointPosition_SendGoalClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SingleJointPosition_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, SingleJointPosition_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_SendGoalClient{client}, nil
}

func (s *SingleJointPosition_SendGoalClient) Send(ctx context.Context, req *SingleJointPosition_SendGoal_Request) (*SingleJointPosition_SendGoal_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SingleJointPosition_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SingleJointPosition_SendGoalServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SingleJointPosition_SendGoalServiceResponseSender) SendResponse(resp *SingleJointPosition_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type SingleJointPosition_SendGoalServiceRequestHandler func(*rclgo.ServiceInfo, *SingleJointPosition_SendGoal_Request, SingleJointPosition_SendGoalServiceResponseSender)

// SingleJointPosition_SendGoalService wraps rclgo.Service to provide type safe helper
// functions
type SingleJointPosition_SendGoalService struct {
	*rclgo.Service
}

// NewSingleJointPosition_SendGoalService creates and returns a new service for the
// SingleJointPosition_SendGoal
func NewSingleJointPosition_SendGoalService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SingleJointPosition_SendGoalServiceRequestHandler) (*SingleJointPosition_SendGoalService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*SingleJointPosition_SendGoal_Request)
		responseSender := SingleJointPosition_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SingleJointPosition_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_SendGoalService{service}, nil
}