// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/single_joint_position.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/SingleJointPosition_GetResult_Request", SingleJointPosition_GetResult_RequestTypeSupport)
	typemap.RegisterMessage("control_msgs/action/SingleJointPosition_GetResult_Request", SingleJointPosition_GetResult_RequestTypeSupport)
}

type SingleJointPosition_GetResult_Request struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
}

// NewSingleJointPosition_GetResult_Request creates a new SingleJointPosition_GetResult_Request with default values.
func NewSingleJointPosition_GetResult_Request() *SingleJointPosition_GetResult_Request {
	self := SingleJointPosition_GetResult_Request{}
	self.SetDefaults()
	return &self
}

func (t *SingleJointPosition_GetResult_Request) Clone() *SingleJointPosition_GetResult_Request {
	c := &SingleJointPosition_GetResult_Request{}
	c.GoalID = *t.GoalID.Clone()
	return c
}

func (t *SingleJointPosition_GetResult_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SingleJointPosition_GetResult_Request) SetDefaults() {
	t.GoalID.SetDefaults()
}

func (t *SingleJointPosition_GetResult_Request) GetTypeSupport() types.MessageTypeSupport {
	return SingleJointPosition_GetResult_RequestTypeSupport
}
func (t *SingleJointPosition_GetResult_Request) GetGoalID() *types.GoalID {
	return (*types.GoalID)(&t.GoalID.Uuid)
}

func (t *SingleJointPosition_GetResult_Request) SetGoalID(id *types.GoalID) {
	t.GoalID.Uuid = *id
}

// SingleJointPosition_GetResult_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SingleJointPosition_GetResult_RequestPublisher struct {
	*rclgo.Publisher
}

// NewSingleJointPosition_GetResult_RequestPublisher creates and returns a new publisher for the
// SingleJointPosition_GetResult_Request
func NewSingleJointPosition_GetResult_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SingleJointPosition_GetResult_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SingleJointPosition_GetResult_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_GetResult_RequestPublisher{pub}, nil
}

func (p *SingleJointPosition_GetResult_RequestPublisher) Publish(msg *SingleJointPosition_GetResult_Request) error {
	return p.Publisher.Publish(msg)
}

// SingleJointPosition_GetResult_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SingleJointPosition_GetResult_RequestSubscription struct {
	*rclgo.Subscription
}

// SingleJointPosition_GetResult_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a SingleJointPosition_GetResult_RequestSubscription.
type SingleJointPosition_GetResult_RequestSubscriptionCallback func(msg *SingleJointPosition_GetResult_Request, info *rclgo.MessageInfo, err error)

// NewSingleJointPosition_GetResult_RequestSubscription creates and returns a new subscription for the
// SingleJointPosition_GetResult_Request
func NewSingleJointPosition_GetResult_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SingleJointPosition_GetResult_RequestSubscriptionCallback) (*SingleJointPosition_GetResult_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SingleJointPosition_GetResult_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SingleJointPosition_GetResult_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_GetResult_RequestSubscription{sub}, nil
}

func (s *SingleJointPosition_GetResult_RequestSubscription) TakeMessage(out *SingleJointPosition_GetResult_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSingleJointPosition_GetResult_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSingleJointPosition_GetResult_RequestSlice(dst, src []SingleJointPosition_GetResult_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SingleJointPosition_GetResult_RequestTypeSupport types.MessageTypeSupport = _SingleJointPosition_GetResult_RequestTypeSupport{}

type _SingleJointPosition_GetResult_RequestTypeSupport struct{}

func (t _SingleJointPosition_GetResult_RequestTypeSupport) New() types.Message {
	return NewSingleJointPosition_GetResult_Request()
}

func (t _SingleJointPosition_GetResult_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__SingleJointPosition_GetResult_Request
	return (unsafe.Pointer)(C.control_msgs__action__SingleJointPosition_GetResult_Request__create())
}

func (t _SingleJointPosition_GetResult_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__SingleJointPosition_GetResult_Request__destroy((*C.control_msgs__action__SingleJointPosition_GetResult_Request)(pointer_to_free))
}

func (t _SingleJointPosition_GetResult_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SingleJointPosition_GetResult_Request)
	mem := (*C.control_msgs__action__SingleJointPosition_GetResult_Request)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
}

func (t _SingleJointPosition_GetResult_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SingleJointPosition_GetResult_Request)
	mem := (*C.control_msgs__action__SingleJointPosition_GetResult_Request)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
}

func (t _SingleJointPosition_GetResult_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__SingleJointPosition_GetResult_Request())
}

type CSingleJointPosition_GetResult_Request = C.control_msgs__action__SingleJointPosition_GetResult_Request
type CSingleJointPosition_GetResult_Request__Sequence = C.control_msgs__action__SingleJointPosition_GetResult_Request__Sequence

func SingleJointPosition_GetResult_Request__Sequence_to_Go(goSlice *[]SingleJointPosition_GetResult_Request, cSlice CSingleJointPosition_GetResult_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SingleJointPosition_GetResult_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SingleJointPosition_GetResult_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SingleJointPosition_GetResult_Request__Sequence_to_C(cSlice *CSingleJointPosition_GetResult_Request__Sequence, goSlice []SingleJointPosition_GetResult_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__SingleJointPosition_GetResult_Request)(C.malloc(C.sizeof_struct_control_msgs__action__SingleJointPosition_GetResult_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SingleJointPosition_GetResult_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SingleJointPosition_GetResult_Request__Array_to_Go(goSlice []SingleJointPosition_GetResult_Request, cSlice []CSingleJointPosition_GetResult_Request) {
	for i := 0; i < len(cSlice); i++ {
		SingleJointPosition_GetResult_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SingleJointPosition_GetResult_Request__Array_to_C(cSlice []CSingleJointPosition_GetResult_Request, goSlice []SingleJointPosition_GetResult_Request) {
	for i := 0; i < len(goSlice); i++ {
		SingleJointPosition_GetResult_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
