// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/single_joint_position.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/SingleJointPosition_SendGoal_Request", SingleJointPosition_SendGoal_RequestTypeSupport)
	typemap.RegisterMessage("control_msgs/action/SingleJointPosition_SendGoal_Request", SingleJointPosition_SendGoal_RequestTypeSupport)
}

type SingleJointPosition_SendGoal_Request struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Goal SingleJointPosition_Goal `yaml:"goal"`
}

// NewSingleJointPosition_SendGoal_Request creates a new SingleJointPosition_SendGoal_Request with default values.
func NewSingleJointPosition_SendGoal_Request() *SingleJointPosition_SendGoal_Request {
	self := SingleJointPosition_SendGoal_Request{}
	self.SetDefaults()
	return &self
}

func (t *SingleJointPosition_SendGoal_Request) Clone() *SingleJointPosition_SendGoal_Request {
	c := &SingleJointPosition_SendGoal_Request{}
	c.GoalID = *t.GoalID.Clone()
	c.Goal = *t.Goal.Clone()
	return c
}

func (t *SingleJointPosition_SendGoal_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SingleJointPosition_SendGoal_Request) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Goal.SetDefaults()
}

func (t *SingleJointPosition_SendGoal_Request) GetTypeSupport() types.MessageTypeSupport {
	return SingleJointPosition_SendGoal_RequestTypeSupport
}
func (t *SingleJointPosition_SendGoal_Request) GetGoalID() *types.GoalID {
	return (*types.GoalID)(&t.GoalID.Uuid)
}

func (t *SingleJointPosition_SendGoal_Request) SetGoalID(id *types.GoalID) {
	t.GoalID.Uuid = *id
}
func (t *SingleJointPosition_SendGoal_Request) GetGoalDescription() types.Message {
	return &t.Goal
}

func (t *SingleJointPosition_SendGoal_Request) SetGoalDescription(desc types.Message) {
	t.Goal = *desc.(*SingleJointPosition_Goal)
}

// SingleJointPosition_SendGoal_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SingleJointPosition_SendGoal_RequestPublisher struct {
	*rclgo.Publisher
}

// NewSingleJointPosition_SendGoal_RequestPublisher creates and returns a new publisher for the
// SingleJointPosition_SendGoal_Request
func NewSingleJointPosition_SendGoal_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SingleJointPosition_SendGoal_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SingleJointPosition_SendGoal_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_SendGoal_RequestPublisher{pub}, nil
}

func (p *SingleJointPosition_SendGoal_RequestPublisher) Publish(msg *SingleJointPosition_SendGoal_Request) error {
	return p.Publisher.Publish(msg)
}

// SingleJointPosition_SendGoal_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SingleJointPosition_SendGoal_RequestSubscription struct {
	*rclgo.Subscription
}

// SingleJointPosition_SendGoal_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a SingleJointPosition_SendGoal_RequestSubscription.
type SingleJointPosition_SendGoal_RequestSubscriptionCallback func(msg *SingleJointPosition_SendGoal_Request, info *rclgo.MessageInfo, err error)

// NewSingleJointPosition_SendGoal_RequestSubscription creates and returns a new subscription for the
// SingleJointPosition_SendGoal_Request
func NewSingleJointPosition_SendGoal_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SingleJointPosition_SendGoal_RequestSubscriptionCallback) (*SingleJointPosition_SendGoal_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SingleJointPosition_SendGoal_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SingleJointPosition_SendGoal_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_SendGoal_RequestSubscription{sub}, nil
}

func (s *SingleJointPosition_SendGoal_RequestSubscription) TakeMessage(out *SingleJointPosition_SendGoal_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSingleJointPosition_SendGoal_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSingleJointPosition_SendGoal_RequestSlice(dst, src []SingleJointPosition_SendGoal_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SingleJointPosition_SendGoal_RequestTypeSupport types.MessageTypeSupport = _SingleJointPosition_SendGoal_RequestTypeSupport{}

type _SingleJointPosition_SendGoal_RequestTypeSupport struct{}

func (t _SingleJointPosition_SendGoal_RequestTypeSupport) New() types.Message {
	return NewSingleJointPosition_SendGoal_Request()
}

func (t _SingleJointPosition_SendGoal_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__SingleJointPosition_SendGoal_Request
	return (unsafe.Pointer)(C.control_msgs__action__SingleJointPosition_SendGoal_Request__create())
}

func (t _SingleJointPosition_SendGoal_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__SingleJointPosition_SendGoal_Request__destroy((*C.control_msgs__action__SingleJointPosition_SendGoal_Request)(pointer_to_free))
}

func (t _SingleJointPosition_SendGoal_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SingleJointPosition_SendGoal_Request)
	mem := (*C.control_msgs__action__SingleJointPosition_SendGoal_Request)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	SingleJointPosition_GoalTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal), &m.Goal)
}

func (t _SingleJointPosition_SendGoal_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SingleJointPosition_SendGoal_Request)
	mem := (*C.control_msgs__action__SingleJointPosition_SendGoal_Request)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	SingleJointPosition_GoalTypeSupport.AsGoStruct(&m.Goal, unsafe.Pointer(&mem.goal))
}

func (t _SingleJointPosition_SendGoal_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__SingleJointPosition_SendGoal_Request())
}

type CSingleJointPosition_SendGoal_Request = C.control_msgs__action__SingleJointPosition_SendGoal_Request
type CSingleJointPosition_SendGoal_Request__Sequence = C.control_msgs__action__SingleJointPosition_SendGoal_Request__Sequence

func SingleJointPosition_SendGoal_Request__Sequence_to_Go(goSlice *[]SingleJointPosition_SendGoal_Request, cSlice CSingleJointPosition_SendGoal_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SingleJointPosition_SendGoal_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SingleJointPosition_SendGoal_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SingleJointPosition_SendGoal_Request__Sequence_to_C(cSlice *CSingleJointPosition_SendGoal_Request__Sequence, goSlice []SingleJointPosition_SendGoal_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__SingleJointPosition_SendGoal_Request)(C.malloc(C.sizeof_struct_control_msgs__action__SingleJointPosition_SendGoal_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SingleJointPosition_SendGoal_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SingleJointPosition_SendGoal_Request__Array_to_Go(goSlice []SingleJointPosition_SendGoal_Request, cSlice []CSingleJointPosition_SendGoal_Request) {
	for i := 0; i < len(cSlice); i++ {
		SingleJointPosition_SendGoal_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SingleJointPosition_SendGoal_Request__Array_to_C(cSlice []CSingleJointPosition_SendGoal_Request, goSlice []SingleJointPosition_SendGoal_Request) {
	for i := 0; i < len(goSlice); i++ {
		SingleJointPosition_SendGoal_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
