// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/action/single_joint_position.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/SingleJointPosition_Goal", SingleJointPosition_GoalTypeSupport)
	typemap.RegisterMessage("control_msgs/action/SingleJointPosition_Goal", SingleJointPosition_GoalTypeSupport)
}

type SingleJointPosition_Goal struct {
	Position float64 `yaml:"position"`
	MinDuration builtin_interfaces_msg.Duration `yaml:"min_duration"`
	MaxVelocity float64 `yaml:"max_velocity"`
}

// NewSingleJointPosition_Goal creates a new SingleJointPosition_Goal with default values.
func NewSingleJointPosition_Goal() *SingleJointPosition_Goal {
	self := SingleJointPosition_Goal{}
	self.SetDefaults()
	return &self
}

func (t *SingleJointPosition_Goal) Clone() *SingleJointPosition_Goal {
	c := &SingleJointPosition_Goal{}
	c.Position = t.Position
	c.MinDuration = *t.MinDuration.Clone()
	c.MaxVelocity = t.MaxVelocity
	return c
}

func (t *SingleJointPosition_Goal) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SingleJointPosition_Goal) SetDefaults() {
	t.Position = 0
	t.MinDuration.SetDefaults()
	t.MaxVelocity = 0
}

func (t *SingleJointPosition_Goal) GetTypeSupport() types.MessageTypeSupport {
	return SingleJointPosition_GoalTypeSupport
}

// SingleJointPosition_GoalPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SingleJointPosition_GoalPublisher struct {
	*rclgo.Publisher
}

// NewSingleJointPosition_GoalPublisher creates and returns a new publisher for the
// SingleJointPosition_Goal
func NewSingleJointPosition_GoalPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SingleJointPosition_GoalPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SingleJointPosition_GoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_GoalPublisher{pub}, nil
}

func (p *SingleJointPosition_GoalPublisher) Publish(msg *SingleJointPosition_Goal) error {
	return p.Publisher.Publish(msg)
}

// SingleJointPosition_GoalSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SingleJointPosition_GoalSubscription struct {
	*rclgo.Subscription
}

// SingleJointPosition_GoalSubscriptionCallback type is used to provide a subscription
// handler function for a SingleJointPosition_GoalSubscription.
type SingleJointPosition_GoalSubscriptionCallback func(msg *SingleJointPosition_Goal, info *rclgo.MessageInfo, err error)

// NewSingleJointPosition_GoalSubscription creates and returns a new subscription for the
// SingleJointPosition_Goal
func NewSingleJointPosition_GoalSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SingleJointPosition_GoalSubscriptionCallback) (*SingleJointPosition_GoalSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SingleJointPosition_Goal
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SingleJointPosition_GoalTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_GoalSubscription{sub}, nil
}

func (s *SingleJointPosition_GoalSubscription) TakeMessage(out *SingleJointPosition_Goal) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSingleJointPosition_GoalSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSingleJointPosition_GoalSlice(dst, src []SingleJointPosition_Goal) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SingleJointPosition_GoalTypeSupport types.MessageTypeSupport = _SingleJointPosition_GoalTypeSupport{}

type _SingleJointPosition_GoalTypeSupport struct{}

func (t _SingleJointPosition_GoalTypeSupport) New() types.Message {
	return NewSingleJointPosition_Goal()
}

func (t _SingleJointPosition_GoalTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__action__SingleJointPosition_Goal
	return (unsafe.Pointer)(C.control_msgs__action__SingleJointPosition_Goal__create())
}

func (t _SingleJointPosition_GoalTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__action__SingleJointPosition_Goal__destroy((*C.control_msgs__action__SingleJointPosition_Goal)(pointer_to_free))
}

func (t _SingleJointPosition_GoalTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SingleJointPosition_Goal)
	mem := (*C.control_msgs__action__SingleJointPosition_Goal)(dst)
	mem.position = C.double(m.Position)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.min_duration), &m.MinDuration)
	mem.max_velocity = C.double(m.MaxVelocity)
}

func (t _SingleJointPosition_GoalTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SingleJointPosition_Goal)
	mem := (*C.control_msgs__action__SingleJointPosition_Goal)(ros2_message_buffer)
	m.Position = float64(mem.position)
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.MinDuration, unsafe.Pointer(&mem.min_duration))
	m.MaxVelocity = float64(mem.max_velocity)
}

func (t _SingleJointPosition_GoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__action__SingleJointPosition_Goal())
}

type CSingleJointPosition_Goal = C.control_msgs__action__SingleJointPosition_Goal
type CSingleJointPosition_Goal__Sequence = C.control_msgs__action__SingleJointPosition_Goal__Sequence

func SingleJointPosition_Goal__Sequence_to_Go(goSlice *[]SingleJointPosition_Goal, cSlice CSingleJointPosition_Goal__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SingleJointPosition_Goal, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SingleJointPosition_GoalTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SingleJointPosition_Goal__Sequence_to_C(cSlice *CSingleJointPosition_Goal__Sequence, goSlice []SingleJointPosition_Goal) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__action__SingleJointPosition_Goal)(C.malloc(C.sizeof_struct_control_msgs__action__SingleJointPosition_Goal * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SingleJointPosition_GoalTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SingleJointPosition_Goal__Array_to_Go(goSlice []SingleJointPosition_Goal, cSlice []CSingleJointPosition_Goal) {
	for i := 0; i < len(cSlice); i++ {
		SingleJointPosition_GoalTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SingleJointPosition_Goal__Array_to_C(cSlice []CSingleJointPosition_Goal, goSlice []SingleJointPosition_Goal) {
	for i := 0; i < len(goSlice); i++ {
		SingleJointPosition_GoalTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
