// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <control_msgs/action/single_joint_position.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("control_msgs/SingleJointPosition_GetResult", SingleJointPosition_GetResultTypeSupport)
	typemap.RegisterService("control_msgs/action/SingleJointPosition_GetResult", SingleJointPosition_GetResultTypeSupport)
}

type _SingleJointPosition_GetResultTypeSupport struct {}

func (s _SingleJointPosition_GetResultTypeSupport) Request() types.MessageTypeSupport {
	return SingleJointPosition_GetResult_RequestTypeSupport
}

func (s _SingleJointPosition_GetResultTypeSupport) Response() types.MessageTypeSupport {
	return SingleJointPosition_GetResult_ResponseTypeSupport
}

func (s _SingleJointPosition_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__control_msgs__action__SingleJointPosition_GetResult())
}

// Modifying this variable is undefined behavior.
var SingleJointPosition_GetResultTypeSupport types.ServiceTypeSupport = _SingleJointPosition_GetResultTypeSupport{}

// SingleJointPosition_GetResultClient wraps rclgo.Client to provide type safe helper
// functions
type SingleJointPosition_GetResultClient struct {
	*rclgo.Client
}

// NewSingleJointPosition_GetResultClient creates and returns a new client for the
// SingleJointPosition_GetResult
func NewSingleJointPosition_GetResultClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SingleJointPosition_GetResultClient, error) {
	client, err := node.NewClient(serviceName, SingleJointPosition_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_GetResultClient{client}, nil
}

func (s *SingleJointPosition_GetResultClient) Send(ctx context.Context, req *SingleJointPosition_GetResult_Request) (*SingleJointPosition_GetResult_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SingleJointPosition_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SingleJointPosition_GetResultServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SingleJointPosition_GetResultServiceResponseSender) SendResponse(resp *SingleJointPosition_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type SingleJointPosition_GetResultServiceRequestHandler func(*rclgo.ServiceInfo, *SingleJointPosition_GetResult_Request, SingleJointPosition_GetResultServiceResponseSender)

// SingleJointPosition_GetResultService wraps rclgo.Service to provide type safe helper
// functions
type SingleJointPosition_GetResultService struct {
	*rclgo.Service
}

// NewSingleJointPosition_GetResultService creates and returns a new service for the
// SingleJointPosition_GetResult
func NewSingleJointPosition_GetResultService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SingleJointPosition_GetResultServiceRequestHandler) (*SingleJointPosition_GetResultService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*SingleJointPosition_GetResult_Request)
		responseSender := SingleJointPosition_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SingleJointPosition_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SingleJointPosition_GetResultService{service}, nil
}