// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/configure_controller.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/ConfigureController_Request", ConfigureController_RequestTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/ConfigureController_Request", ConfigureController_RequestTypeSupport)
}

type ConfigureController_Request struct {
	Name string `yaml:"name"`
}

// NewConfigureController_Request creates a new ConfigureController_Request with default values.
func NewConfigureController_Request() *ConfigureController_Request {
	self := ConfigureController_Request{}
	self.SetDefaults()
	return &self
}

func (t *ConfigureController_Request) Clone() *ConfigureController_Request {
	c := &ConfigureController_Request{}
	c.Name = t.Name
	return c
}

func (t *ConfigureController_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ConfigureController_Request) SetDefaults() {
	t.Name = ""
}

func (t *ConfigureController_Request) GetTypeSupport() types.MessageTypeSupport {
	return ConfigureController_RequestTypeSupport
}

// ConfigureController_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ConfigureController_RequestPublisher struct {
	*rclgo.Publisher
}

// NewConfigureController_RequestPublisher creates and returns a new publisher for the
// ConfigureController_Request
func NewConfigureController_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ConfigureController_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ConfigureController_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ConfigureController_RequestPublisher{pub}, nil
}

func (p *ConfigureController_RequestPublisher) Publish(msg *ConfigureController_Request) error {
	return p.Publisher.Publish(msg)
}

// ConfigureController_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ConfigureController_RequestSubscription struct {
	*rclgo.Subscription
}

// ConfigureController_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a ConfigureController_RequestSubscription.
type ConfigureController_RequestSubscriptionCallback func(msg *ConfigureController_Request, info *rclgo.MessageInfo, err error)

// NewConfigureController_RequestSubscription creates and returns a new subscription for the
// ConfigureController_Request
func NewConfigureController_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ConfigureController_RequestSubscriptionCallback) (*ConfigureController_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ConfigureController_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ConfigureController_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ConfigureController_RequestSubscription{sub}, nil
}

func (s *ConfigureController_RequestSubscription) TakeMessage(out *ConfigureController_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneConfigureController_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneConfigureController_RequestSlice(dst, src []ConfigureController_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ConfigureController_RequestTypeSupport types.MessageTypeSupport = _ConfigureController_RequestTypeSupport{}

type _ConfigureController_RequestTypeSupport struct{}

func (t _ConfigureController_RequestTypeSupport) New() types.Message {
	return NewConfigureController_Request()
}

func (t _ConfigureController_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__ConfigureController_Request
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__ConfigureController_Request__create())
}

func (t _ConfigureController_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__ConfigureController_Request__destroy((*C.controller_manager_msgs__srv__ConfigureController_Request)(pointer_to_free))
}

func (t _ConfigureController_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ConfigureController_Request)
	mem := (*C.controller_manager_msgs__srv__ConfigureController_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.name), m.Name)
}

func (t _ConfigureController_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ConfigureController_Request)
	mem := (*C.controller_manager_msgs__srv__ConfigureController_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Name, unsafe.Pointer(&mem.name))
}

func (t _ConfigureController_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__ConfigureController_Request())
}

type CConfigureController_Request = C.controller_manager_msgs__srv__ConfigureController_Request
type CConfigureController_Request__Sequence = C.controller_manager_msgs__srv__ConfigureController_Request__Sequence

func ConfigureController_Request__Sequence_to_Go(goSlice *[]ConfigureController_Request, cSlice CConfigureController_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ConfigureController_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ConfigureController_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ConfigureController_Request__Sequence_to_C(cSlice *CConfigureController_Request__Sequence, goSlice []ConfigureController_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__ConfigureController_Request)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__ConfigureController_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ConfigureController_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ConfigureController_Request__Array_to_Go(goSlice []ConfigureController_Request, cSlice []CConfigureController_Request) {
	for i := 0; i < len(cSlice); i++ {
		ConfigureController_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ConfigureController_Request__Array_to_C(cSlice []CConfigureController_Request, goSlice []ConfigureController_Request) {
	for i := 0; i < len(goSlice); i++ {
		ConfigureController_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
