// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/configure_controller.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/ConfigureController_Response", ConfigureController_ResponseTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/ConfigureController_Response", ConfigureController_ResponseTypeSupport)
}

type ConfigureController_Response struct {
	Ok bool `yaml:"ok"`
}

// NewConfigureController_Response creates a new ConfigureController_Response with default values.
func NewConfigureController_Response() *ConfigureController_Response {
	self := ConfigureController_Response{}
	self.SetDefaults()
	return &self
}

func (t *ConfigureController_Response) Clone() *ConfigureController_Response {
	c := &ConfigureController_Response{}
	c.Ok = t.Ok
	return c
}

func (t *ConfigureController_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ConfigureController_Response) SetDefaults() {
	t.Ok = false
}

func (t *ConfigureController_Response) GetTypeSupport() types.MessageTypeSupport {
	return ConfigureController_ResponseTypeSupport
}

// ConfigureController_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ConfigureController_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewConfigureController_ResponsePublisher creates and returns a new publisher for the
// ConfigureController_Response
func NewConfigureController_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ConfigureController_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ConfigureController_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ConfigureController_ResponsePublisher{pub}, nil
}

func (p *ConfigureController_ResponsePublisher) Publish(msg *ConfigureController_Response) error {
	return p.Publisher.Publish(msg)
}

// ConfigureController_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ConfigureController_ResponseSubscription struct {
	*rclgo.Subscription
}

// ConfigureController_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ConfigureController_ResponseSubscription.
type ConfigureController_ResponseSubscriptionCallback func(msg *ConfigureController_Response, info *rclgo.MessageInfo, err error)

// NewConfigureController_ResponseSubscription creates and returns a new subscription for the
// ConfigureController_Response
func NewConfigureController_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ConfigureController_ResponseSubscriptionCallback) (*ConfigureController_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ConfigureController_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ConfigureController_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ConfigureController_ResponseSubscription{sub}, nil
}

func (s *ConfigureController_ResponseSubscription) TakeMessage(out *ConfigureController_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneConfigureController_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneConfigureController_ResponseSlice(dst, src []ConfigureController_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ConfigureController_ResponseTypeSupport types.MessageTypeSupport = _ConfigureController_ResponseTypeSupport{}

type _ConfigureController_ResponseTypeSupport struct{}

func (t _ConfigureController_ResponseTypeSupport) New() types.Message {
	return NewConfigureController_Response()
}

func (t _ConfigureController_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__ConfigureController_Response
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__ConfigureController_Response__create())
}

func (t _ConfigureController_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__ConfigureController_Response__destroy((*C.controller_manager_msgs__srv__ConfigureController_Response)(pointer_to_free))
}

func (t _ConfigureController_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ConfigureController_Response)
	mem := (*C.controller_manager_msgs__srv__ConfigureController_Response)(dst)
	mem.ok = C.bool(m.Ok)
}

func (t _ConfigureController_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ConfigureController_Response)
	mem := (*C.controller_manager_msgs__srv__ConfigureController_Response)(ros2_message_buffer)
	m.Ok = bool(mem.ok)
}

func (t _ConfigureController_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__ConfigureController_Response())
}

type CConfigureController_Response = C.controller_manager_msgs__srv__ConfigureController_Response
type CConfigureController_Response__Sequence = C.controller_manager_msgs__srv__ConfigureController_Response__Sequence

func ConfigureController_Response__Sequence_to_Go(goSlice *[]ConfigureController_Response, cSlice CConfigureController_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ConfigureController_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ConfigureController_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ConfigureController_Response__Sequence_to_C(cSlice *CConfigureController_Response__Sequence, goSlice []ConfigureController_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__ConfigureController_Response)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__ConfigureController_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ConfigureController_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ConfigureController_Response__Array_to_Go(goSlice []ConfigureController_Response, cSlice []CConfigureController_Response) {
	for i := 0; i < len(cSlice); i++ {
		ConfigureController_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ConfigureController_Response__Array_to_C(cSlice []CConfigureController_Response, goSlice []ConfigureController_Response) {
	for i := 0; i < len(goSlice); i++ {
		ConfigureController_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
