// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <controller_manager_msgs/srv/list_controllers.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("controller_manager_msgs/ListControllers", ListControllersTypeSupport)
	typemap.RegisterService("controller_manager_msgs/srv/ListControllers", ListControllersTypeSupport)
}

type _ListControllersTypeSupport struct {}

func (s _ListControllersTypeSupport) Request() types.MessageTypeSupport {
	return ListControllers_RequestTypeSupport
}

func (s _ListControllersTypeSupport) Response() types.MessageTypeSupport {
	return ListControllers_ResponseTypeSupport
}

func (s _ListControllersTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__controller_manager_msgs__srv__ListControllers())
}

// Modifying this variable is undefined behavior.
var ListControllersTypeSupport types.ServiceTypeSupport = _ListControllersTypeSupport{}

// ListControllersClient wraps rclgo.Client to provide type safe helper
// functions
type ListControllersClient struct {
	*rclgo.Client
}

// NewListControllersClient creates and returns a new client for the
// ListControllers
func NewListControllersClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ListControllersClient, error) {
	client, err := node.NewClient(serviceName, ListControllersTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListControllersClient{client}, nil
}

func (s *ListControllersClient) Send(ctx context.Context, req *ListControllers_Request) (*ListControllers_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ListControllers_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ListControllersServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ListControllersServiceResponseSender) SendResponse(resp *ListControllers_Response) error {
	return s.sender.SendResponse(resp)
}

type ListControllersServiceRequestHandler func(*rclgo.ServiceInfo, *ListControllers_Request, ListControllersServiceResponseSender)

// ListControllersService wraps rclgo.Service to provide type safe helper
// functions
type ListControllersService struct {
	*rclgo.Service
}

// NewListControllersService creates and returns a new service for the
// ListControllers
func NewListControllersService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ListControllersServiceRequestHandler) (*ListControllersService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ListControllers_Request)
		responseSender := ListControllersServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ListControllersTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ListControllersService{service}, nil
}