// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/list_hardware_components.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/ListHardwareComponents_Request", ListHardwareComponents_RequestTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/ListHardwareComponents_Request", ListHardwareComponents_RequestTypeSupport)
}

type ListHardwareComponents_Request struct {
}

// NewListHardwareComponents_Request creates a new ListHardwareComponents_Request with default values.
func NewListHardwareComponents_Request() *ListHardwareComponents_Request {
	self := ListHardwareComponents_Request{}
	self.SetDefaults()
	return &self
}

func (t *ListHardwareComponents_Request) Clone() *ListHardwareComponents_Request {
	c := &ListHardwareComponents_Request{}
	return c
}

func (t *ListHardwareComponents_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ListHardwareComponents_Request) SetDefaults() {
}

func (t *ListHardwareComponents_Request) GetTypeSupport() types.MessageTypeSupport {
	return ListHardwareComponents_RequestTypeSupport
}

// ListHardwareComponents_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ListHardwareComponents_RequestPublisher struct {
	*rclgo.Publisher
}

// NewListHardwareComponents_RequestPublisher creates and returns a new publisher for the
// ListHardwareComponents_Request
func NewListHardwareComponents_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ListHardwareComponents_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ListHardwareComponents_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListHardwareComponents_RequestPublisher{pub}, nil
}

func (p *ListHardwareComponents_RequestPublisher) Publish(msg *ListHardwareComponents_Request) error {
	return p.Publisher.Publish(msg)
}

// ListHardwareComponents_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ListHardwareComponents_RequestSubscription struct {
	*rclgo.Subscription
}

// ListHardwareComponents_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a ListHardwareComponents_RequestSubscription.
type ListHardwareComponents_RequestSubscriptionCallback func(msg *ListHardwareComponents_Request, info *rclgo.MessageInfo, err error)

// NewListHardwareComponents_RequestSubscription creates and returns a new subscription for the
// ListHardwareComponents_Request
func NewListHardwareComponents_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ListHardwareComponents_RequestSubscriptionCallback) (*ListHardwareComponents_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ListHardwareComponents_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ListHardwareComponents_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ListHardwareComponents_RequestSubscription{sub}, nil
}

func (s *ListHardwareComponents_RequestSubscription) TakeMessage(out *ListHardwareComponents_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneListHardwareComponents_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneListHardwareComponents_RequestSlice(dst, src []ListHardwareComponents_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ListHardwareComponents_RequestTypeSupport types.MessageTypeSupport = _ListHardwareComponents_RequestTypeSupport{}

type _ListHardwareComponents_RequestTypeSupport struct{}

func (t _ListHardwareComponents_RequestTypeSupport) New() types.Message {
	return NewListHardwareComponents_Request()
}

func (t _ListHardwareComponents_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__ListHardwareComponents_Request
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__ListHardwareComponents_Request__create())
}

func (t _ListHardwareComponents_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__ListHardwareComponents_Request__destroy((*C.controller_manager_msgs__srv__ListHardwareComponents_Request)(pointer_to_free))
}

func (t _ListHardwareComponents_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _ListHardwareComponents_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _ListHardwareComponents_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__ListHardwareComponents_Request())
}

type CListHardwareComponents_Request = C.controller_manager_msgs__srv__ListHardwareComponents_Request
type CListHardwareComponents_Request__Sequence = C.controller_manager_msgs__srv__ListHardwareComponents_Request__Sequence

func ListHardwareComponents_Request__Sequence_to_Go(goSlice *[]ListHardwareComponents_Request, cSlice CListHardwareComponents_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ListHardwareComponents_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ListHardwareComponents_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ListHardwareComponents_Request__Sequence_to_C(cSlice *CListHardwareComponents_Request__Sequence, goSlice []ListHardwareComponents_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__ListHardwareComponents_Request)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__ListHardwareComponents_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ListHardwareComponents_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ListHardwareComponents_Request__Array_to_Go(goSlice []ListHardwareComponents_Request, cSlice []CListHardwareComponents_Request) {
	for i := 0; i < len(cSlice); i++ {
		ListHardwareComponents_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ListHardwareComponents_Request__Array_to_C(cSlice []CListHardwareComponents_Request, goSlice []ListHardwareComponents_Request) {
	for i := 0; i < len(goSlice); i++ {
		ListHardwareComponents_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
