// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	controller_manager_msgs_msg "msgs/controller_manager_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/list_controllers.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/ListControllers_Response", ListControllers_ResponseTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/ListControllers_Response", ListControllers_ResponseTypeSupport)
}

type ListControllers_Response struct {
	Controller []controller_manager_msgs_msg.ControllerState `yaml:"controller"`
}

// NewListControllers_Response creates a new ListControllers_Response with default values.
func NewListControllers_Response() *ListControllers_Response {
	self := ListControllers_Response{}
	self.SetDefaults()
	return &self
}

func (t *ListControllers_Response) Clone() *ListControllers_Response {
	c := &ListControllers_Response{}
	if t.Controller != nil {
		c.Controller = make([]controller_manager_msgs_msg.ControllerState, len(t.Controller))
		controller_manager_msgs_msg.CloneControllerStateSlice(c.Controller, t.Controller)
	}
	return c
}

func (t *ListControllers_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ListControllers_Response) SetDefaults() {
	t.Controller = nil
}

func (t *ListControllers_Response) GetTypeSupport() types.MessageTypeSupport {
	return ListControllers_ResponseTypeSupport
}

// ListControllers_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ListControllers_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewListControllers_ResponsePublisher creates and returns a new publisher for the
// ListControllers_Response
func NewListControllers_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ListControllers_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ListControllers_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListControllers_ResponsePublisher{pub}, nil
}

func (p *ListControllers_ResponsePublisher) Publish(msg *ListControllers_Response) error {
	return p.Publisher.Publish(msg)
}

// ListControllers_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ListControllers_ResponseSubscription struct {
	*rclgo.Subscription
}

// ListControllers_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ListControllers_ResponseSubscription.
type ListControllers_ResponseSubscriptionCallback func(msg *ListControllers_Response, info *rclgo.MessageInfo, err error)

// NewListControllers_ResponseSubscription creates and returns a new subscription for the
// ListControllers_Response
func NewListControllers_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ListControllers_ResponseSubscriptionCallback) (*ListControllers_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ListControllers_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ListControllers_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ListControllers_ResponseSubscription{sub}, nil
}

func (s *ListControllers_ResponseSubscription) TakeMessage(out *ListControllers_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneListControllers_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneListControllers_ResponseSlice(dst, src []ListControllers_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ListControllers_ResponseTypeSupport types.MessageTypeSupport = _ListControllers_ResponseTypeSupport{}

type _ListControllers_ResponseTypeSupport struct{}

func (t _ListControllers_ResponseTypeSupport) New() types.Message {
	return NewListControllers_Response()
}

func (t _ListControllers_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__ListControllers_Response
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__ListControllers_Response__create())
}

func (t _ListControllers_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__ListControllers_Response__destroy((*C.controller_manager_msgs__srv__ListControllers_Response)(pointer_to_free))
}

func (t _ListControllers_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ListControllers_Response)
	mem := (*C.controller_manager_msgs__srv__ListControllers_Response)(dst)
	controller_manager_msgs_msg.ControllerState__Sequence_to_C((*controller_manager_msgs_msg.CControllerState__Sequence)(unsafe.Pointer(&mem.controller)), m.Controller)
}

func (t _ListControllers_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ListControllers_Response)
	mem := (*C.controller_manager_msgs__srv__ListControllers_Response)(ros2_message_buffer)
	controller_manager_msgs_msg.ControllerState__Sequence_to_Go(&m.Controller, *(*controller_manager_msgs_msg.CControllerState__Sequence)(unsafe.Pointer(&mem.controller)))
}

func (t _ListControllers_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__ListControllers_Response())
}

type CListControllers_Response = C.controller_manager_msgs__srv__ListControllers_Response
type CListControllers_Response__Sequence = C.controller_manager_msgs__srv__ListControllers_Response__Sequence

func ListControllers_Response__Sequence_to_Go(goSlice *[]ListControllers_Response, cSlice CListControllers_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ListControllers_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ListControllers_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ListControllers_Response__Sequence_to_C(cSlice *CListControllers_Response__Sequence, goSlice []ListControllers_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__ListControllers_Response)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__ListControllers_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ListControllers_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ListControllers_Response__Array_to_Go(goSlice []ListControllers_Response, cSlice []CListControllers_Response) {
	for i := 0; i < len(cSlice); i++ {
		ListControllers_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ListControllers_Response__Array_to_C(cSlice []CListControllers_Response, goSlice []ListControllers_Response) {
	for i := 0; i < len(goSlice); i++ {
		ListControllers_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
