// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/list_controller_types.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/ListControllerTypes_Request", ListControllerTypes_RequestTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/ListControllerTypes_Request", ListControllerTypes_RequestTypeSupport)
}

type ListControllerTypes_Request struct {
}

// NewListControllerTypes_Request creates a new ListControllerTypes_Request with default values.
func NewListControllerTypes_Request() *ListControllerTypes_Request {
	self := ListControllerTypes_Request{}
	self.SetDefaults()
	return &self
}

func (t *ListControllerTypes_Request) Clone() *ListControllerTypes_Request {
	c := &ListControllerTypes_Request{}
	return c
}

func (t *ListControllerTypes_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ListControllerTypes_Request) SetDefaults() {
}

func (t *ListControllerTypes_Request) GetTypeSupport() types.MessageTypeSupport {
	return ListControllerTypes_RequestTypeSupport
}

// ListControllerTypes_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ListControllerTypes_RequestPublisher struct {
	*rclgo.Publisher
}

// NewListControllerTypes_RequestPublisher creates and returns a new publisher for the
// ListControllerTypes_Request
func NewListControllerTypes_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ListControllerTypes_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ListControllerTypes_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListControllerTypes_RequestPublisher{pub}, nil
}

func (p *ListControllerTypes_RequestPublisher) Publish(msg *ListControllerTypes_Request) error {
	return p.Publisher.Publish(msg)
}

// ListControllerTypes_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ListControllerTypes_RequestSubscription struct {
	*rclgo.Subscription
}

// ListControllerTypes_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a ListControllerTypes_RequestSubscription.
type ListControllerTypes_RequestSubscriptionCallback func(msg *ListControllerTypes_Request, info *rclgo.MessageInfo, err error)

// NewListControllerTypes_RequestSubscription creates and returns a new subscription for the
// ListControllerTypes_Request
func NewListControllerTypes_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ListControllerTypes_RequestSubscriptionCallback) (*ListControllerTypes_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ListControllerTypes_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ListControllerTypes_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ListControllerTypes_RequestSubscription{sub}, nil
}

func (s *ListControllerTypes_RequestSubscription) TakeMessage(out *ListControllerTypes_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneListControllerTypes_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneListControllerTypes_RequestSlice(dst, src []ListControllerTypes_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ListControllerTypes_RequestTypeSupport types.MessageTypeSupport = _ListControllerTypes_RequestTypeSupport{}

type _ListControllerTypes_RequestTypeSupport struct{}

func (t _ListControllerTypes_RequestTypeSupport) New() types.Message {
	return NewListControllerTypes_Request()
}

func (t _ListControllerTypes_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__ListControllerTypes_Request
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__ListControllerTypes_Request__create())
}

func (t _ListControllerTypes_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__ListControllerTypes_Request__destroy((*C.controller_manager_msgs__srv__ListControllerTypes_Request)(pointer_to_free))
}

func (t _ListControllerTypes_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _ListControllerTypes_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _ListControllerTypes_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__ListControllerTypes_Request())
}

type CListControllerTypes_Request = C.controller_manager_msgs__srv__ListControllerTypes_Request
type CListControllerTypes_Request__Sequence = C.controller_manager_msgs__srv__ListControllerTypes_Request__Sequence

func ListControllerTypes_Request__Sequence_to_Go(goSlice *[]ListControllerTypes_Request, cSlice CListControllerTypes_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ListControllerTypes_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ListControllerTypes_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ListControllerTypes_Request__Sequence_to_C(cSlice *CListControllerTypes_Request__Sequence, goSlice []ListControllerTypes_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__ListControllerTypes_Request)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__ListControllerTypes_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ListControllerTypes_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ListControllerTypes_Request__Array_to_Go(goSlice []ListControllerTypes_Request, cSlice []CListControllerTypes_Request) {
	for i := 0; i < len(cSlice); i++ {
		ListControllerTypes_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ListControllerTypes_Request__Array_to_C(cSlice []CListControllerTypes_Request, goSlice []ListControllerTypes_Request) {
	for i := 0; i < len(goSlice); i++ {
		ListControllerTypes_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
