// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/list_hardware_interfaces.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/ListHardwareInterfaces_Request", ListHardwareInterfaces_RequestTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/ListHardwareInterfaces_Request", ListHardwareInterfaces_RequestTypeSupport)
}

type ListHardwareInterfaces_Request struct {
}

// NewListHardwareInterfaces_Request creates a new ListHardwareInterfaces_Request with default values.
func NewListHardwareInterfaces_Request() *ListHardwareInterfaces_Request {
	self := ListHardwareInterfaces_Request{}
	self.SetDefaults()
	return &self
}

func (t *ListHardwareInterfaces_Request) Clone() *ListHardwareInterfaces_Request {
	c := &ListHardwareInterfaces_Request{}
	return c
}

func (t *ListHardwareInterfaces_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ListHardwareInterfaces_Request) SetDefaults() {
}

func (t *ListHardwareInterfaces_Request) GetTypeSupport() types.MessageTypeSupport {
	return ListHardwareInterfaces_RequestTypeSupport
}

// ListHardwareInterfaces_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ListHardwareInterfaces_RequestPublisher struct {
	*rclgo.Publisher
}

// NewListHardwareInterfaces_RequestPublisher creates and returns a new publisher for the
// ListHardwareInterfaces_Request
func NewListHardwareInterfaces_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ListHardwareInterfaces_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ListHardwareInterfaces_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListHardwareInterfaces_RequestPublisher{pub}, nil
}

func (p *ListHardwareInterfaces_RequestPublisher) Publish(msg *ListHardwareInterfaces_Request) error {
	return p.Publisher.Publish(msg)
}

// ListHardwareInterfaces_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ListHardwareInterfaces_RequestSubscription struct {
	*rclgo.Subscription
}

// ListHardwareInterfaces_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a ListHardwareInterfaces_RequestSubscription.
type ListHardwareInterfaces_RequestSubscriptionCallback func(msg *ListHardwareInterfaces_Request, info *rclgo.MessageInfo, err error)

// NewListHardwareInterfaces_RequestSubscription creates and returns a new subscription for the
// ListHardwareInterfaces_Request
func NewListHardwareInterfaces_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ListHardwareInterfaces_RequestSubscriptionCallback) (*ListHardwareInterfaces_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ListHardwareInterfaces_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ListHardwareInterfaces_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ListHardwareInterfaces_RequestSubscription{sub}, nil
}

func (s *ListHardwareInterfaces_RequestSubscription) TakeMessage(out *ListHardwareInterfaces_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneListHardwareInterfaces_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneListHardwareInterfaces_RequestSlice(dst, src []ListHardwareInterfaces_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ListHardwareInterfaces_RequestTypeSupport types.MessageTypeSupport = _ListHardwareInterfaces_RequestTypeSupport{}

type _ListHardwareInterfaces_RequestTypeSupport struct{}

func (t _ListHardwareInterfaces_RequestTypeSupport) New() types.Message {
	return NewListHardwareInterfaces_Request()
}

func (t _ListHardwareInterfaces_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__ListHardwareInterfaces_Request
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__ListHardwareInterfaces_Request__create())
}

func (t _ListHardwareInterfaces_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__ListHardwareInterfaces_Request__destroy((*C.controller_manager_msgs__srv__ListHardwareInterfaces_Request)(pointer_to_free))
}

func (t _ListHardwareInterfaces_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _ListHardwareInterfaces_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _ListHardwareInterfaces_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__ListHardwareInterfaces_Request())
}

type CListHardwareInterfaces_Request = C.controller_manager_msgs__srv__ListHardwareInterfaces_Request
type CListHardwareInterfaces_Request__Sequence = C.controller_manager_msgs__srv__ListHardwareInterfaces_Request__Sequence

func ListHardwareInterfaces_Request__Sequence_to_Go(goSlice *[]ListHardwareInterfaces_Request, cSlice CListHardwareInterfaces_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ListHardwareInterfaces_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ListHardwareInterfaces_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ListHardwareInterfaces_Request__Sequence_to_C(cSlice *CListHardwareInterfaces_Request__Sequence, goSlice []ListHardwareInterfaces_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__ListHardwareInterfaces_Request)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__ListHardwareInterfaces_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ListHardwareInterfaces_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ListHardwareInterfaces_Request__Array_to_Go(goSlice []ListHardwareInterfaces_Request, cSlice []CListHardwareInterfaces_Request) {
	for i := 0; i < len(cSlice); i++ {
		ListHardwareInterfaces_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ListHardwareInterfaces_Request__Array_to_C(cSlice []CListHardwareInterfaces_Request, goSlice []ListHardwareInterfaces_Request) {
	for i := 0; i < len(goSlice); i++ {
		ListHardwareInterfaces_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
