// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/list_controller_types.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/ListControllerTypes_Response", ListControllerTypes_ResponseTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/ListControllerTypes_Response", ListControllerTypes_ResponseTypeSupport)
}

type ListControllerTypes_Response struct {
	Types []string `yaml:"types"`
	BaseClasses []string `yaml:"base_classes"`
}

// NewListControllerTypes_Response creates a new ListControllerTypes_Response with default values.
func NewListControllerTypes_Response() *ListControllerTypes_Response {
	self := ListControllerTypes_Response{}
	self.SetDefaults()
	return &self
}

func (t *ListControllerTypes_Response) Clone() *ListControllerTypes_Response {
	c := &ListControllerTypes_Response{}
	if t.Types != nil {
		c.Types = make([]string, len(t.Types))
		copy(c.Types, t.Types)
	}
	if t.BaseClasses != nil {
		c.BaseClasses = make([]string, len(t.BaseClasses))
		copy(c.BaseClasses, t.BaseClasses)
	}
	return c
}

func (t *ListControllerTypes_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ListControllerTypes_Response) SetDefaults() {
	t.Types = nil
	t.BaseClasses = nil
}

func (t *ListControllerTypes_Response) GetTypeSupport() types.MessageTypeSupport {
	return ListControllerTypes_ResponseTypeSupport
}

// ListControllerTypes_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ListControllerTypes_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewListControllerTypes_ResponsePublisher creates and returns a new publisher for the
// ListControllerTypes_Response
func NewListControllerTypes_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ListControllerTypes_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ListControllerTypes_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListControllerTypes_ResponsePublisher{pub}, nil
}

func (p *ListControllerTypes_ResponsePublisher) Publish(msg *ListControllerTypes_Response) error {
	return p.Publisher.Publish(msg)
}

// ListControllerTypes_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ListControllerTypes_ResponseSubscription struct {
	*rclgo.Subscription
}

// ListControllerTypes_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ListControllerTypes_ResponseSubscription.
type ListControllerTypes_ResponseSubscriptionCallback func(msg *ListControllerTypes_Response, info *rclgo.MessageInfo, err error)

// NewListControllerTypes_ResponseSubscription creates and returns a new subscription for the
// ListControllerTypes_Response
func NewListControllerTypes_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ListControllerTypes_ResponseSubscriptionCallback) (*ListControllerTypes_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ListControllerTypes_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ListControllerTypes_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ListControllerTypes_ResponseSubscription{sub}, nil
}

func (s *ListControllerTypes_ResponseSubscription) TakeMessage(out *ListControllerTypes_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneListControllerTypes_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneListControllerTypes_ResponseSlice(dst, src []ListControllerTypes_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ListControllerTypes_ResponseTypeSupport types.MessageTypeSupport = _ListControllerTypes_ResponseTypeSupport{}

type _ListControllerTypes_ResponseTypeSupport struct{}

func (t _ListControllerTypes_ResponseTypeSupport) New() types.Message {
	return NewListControllerTypes_Response()
}

func (t _ListControllerTypes_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__ListControllerTypes_Response
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__ListControllerTypes_Response__create())
}

func (t _ListControllerTypes_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__ListControllerTypes_Response__destroy((*C.controller_manager_msgs__srv__ListControllerTypes_Response)(pointer_to_free))
}

func (t _ListControllerTypes_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ListControllerTypes_Response)
	mem := (*C.controller_manager_msgs__srv__ListControllerTypes_Response)(dst)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.types)), m.Types)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.base_classes)), m.BaseClasses)
}

func (t _ListControllerTypes_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ListControllerTypes_Response)
	mem := (*C.controller_manager_msgs__srv__ListControllerTypes_Response)(ros2_message_buffer)
	primitives.String__Sequence_to_Go(&m.Types, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.types)))
	primitives.String__Sequence_to_Go(&m.BaseClasses, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.base_classes)))
}

func (t _ListControllerTypes_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__ListControllerTypes_Response())
}

type CListControllerTypes_Response = C.controller_manager_msgs__srv__ListControllerTypes_Response
type CListControllerTypes_Response__Sequence = C.controller_manager_msgs__srv__ListControllerTypes_Response__Sequence

func ListControllerTypes_Response__Sequence_to_Go(goSlice *[]ListControllerTypes_Response, cSlice CListControllerTypes_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ListControllerTypes_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ListControllerTypes_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ListControllerTypes_Response__Sequence_to_C(cSlice *CListControllerTypes_Response__Sequence, goSlice []ListControllerTypes_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__ListControllerTypes_Response)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__ListControllerTypes_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ListControllerTypes_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ListControllerTypes_Response__Array_to_Go(goSlice []ListControllerTypes_Response, cSlice []CListControllerTypes_Response) {
	for i := 0; i < len(cSlice); i++ {
		ListControllerTypes_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ListControllerTypes_Response__Array_to_C(cSlice []CListControllerTypes_Response, goSlice []ListControllerTypes_Response) {
	for i := 0; i < len(goSlice); i++ {
		ListControllerTypes_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
