// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/reload_controller_libraries.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/ReloadControllerLibraries_Response", ReloadControllerLibraries_ResponseTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/ReloadControllerLibraries_Response", ReloadControllerLibraries_ResponseTypeSupport)
}

type ReloadControllerLibraries_Response struct {
	Ok bool `yaml:"ok"`
}

// NewReloadControllerLibraries_Response creates a new ReloadControllerLibraries_Response with default values.
func NewReloadControllerLibraries_Response() *ReloadControllerLibraries_Response {
	self := ReloadControllerLibraries_Response{}
	self.SetDefaults()
	return &self
}

func (t *ReloadControllerLibraries_Response) Clone() *ReloadControllerLibraries_Response {
	c := &ReloadControllerLibraries_Response{}
	c.Ok = t.Ok
	return c
}

func (t *ReloadControllerLibraries_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ReloadControllerLibraries_Response) SetDefaults() {
	t.Ok = false
}

func (t *ReloadControllerLibraries_Response) GetTypeSupport() types.MessageTypeSupport {
	return ReloadControllerLibraries_ResponseTypeSupport
}

// ReloadControllerLibraries_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ReloadControllerLibraries_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewReloadControllerLibraries_ResponsePublisher creates and returns a new publisher for the
// ReloadControllerLibraries_Response
func NewReloadControllerLibraries_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ReloadControllerLibraries_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ReloadControllerLibraries_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ReloadControllerLibraries_ResponsePublisher{pub}, nil
}

func (p *ReloadControllerLibraries_ResponsePublisher) Publish(msg *ReloadControllerLibraries_Response) error {
	return p.Publisher.Publish(msg)
}

// ReloadControllerLibraries_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ReloadControllerLibraries_ResponseSubscription struct {
	*rclgo.Subscription
}

// ReloadControllerLibraries_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ReloadControllerLibraries_ResponseSubscription.
type ReloadControllerLibraries_ResponseSubscriptionCallback func(msg *ReloadControllerLibraries_Response, info *rclgo.MessageInfo, err error)

// NewReloadControllerLibraries_ResponseSubscription creates and returns a new subscription for the
// ReloadControllerLibraries_Response
func NewReloadControllerLibraries_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ReloadControllerLibraries_ResponseSubscriptionCallback) (*ReloadControllerLibraries_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ReloadControllerLibraries_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ReloadControllerLibraries_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ReloadControllerLibraries_ResponseSubscription{sub}, nil
}

func (s *ReloadControllerLibraries_ResponseSubscription) TakeMessage(out *ReloadControllerLibraries_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneReloadControllerLibraries_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneReloadControllerLibraries_ResponseSlice(dst, src []ReloadControllerLibraries_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ReloadControllerLibraries_ResponseTypeSupport types.MessageTypeSupport = _ReloadControllerLibraries_ResponseTypeSupport{}

type _ReloadControllerLibraries_ResponseTypeSupport struct{}

func (t _ReloadControllerLibraries_ResponseTypeSupport) New() types.Message {
	return NewReloadControllerLibraries_Response()
}

func (t _ReloadControllerLibraries_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__ReloadControllerLibraries_Response
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__ReloadControllerLibraries_Response__create())
}

func (t _ReloadControllerLibraries_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__ReloadControllerLibraries_Response__destroy((*C.controller_manager_msgs__srv__ReloadControllerLibraries_Response)(pointer_to_free))
}

func (t _ReloadControllerLibraries_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ReloadControllerLibraries_Response)
	mem := (*C.controller_manager_msgs__srv__ReloadControllerLibraries_Response)(dst)
	mem.ok = C.bool(m.Ok)
}

func (t _ReloadControllerLibraries_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ReloadControllerLibraries_Response)
	mem := (*C.controller_manager_msgs__srv__ReloadControllerLibraries_Response)(ros2_message_buffer)
	m.Ok = bool(mem.ok)
}

func (t _ReloadControllerLibraries_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__ReloadControllerLibraries_Response())
}

type CReloadControllerLibraries_Response = C.controller_manager_msgs__srv__ReloadControllerLibraries_Response
type CReloadControllerLibraries_Response__Sequence = C.controller_manager_msgs__srv__ReloadControllerLibraries_Response__Sequence

func ReloadControllerLibraries_Response__Sequence_to_Go(goSlice *[]ReloadControllerLibraries_Response, cSlice CReloadControllerLibraries_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ReloadControllerLibraries_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ReloadControllerLibraries_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ReloadControllerLibraries_Response__Sequence_to_C(cSlice *CReloadControllerLibraries_Response__Sequence, goSlice []ReloadControllerLibraries_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__ReloadControllerLibraries_Response)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__ReloadControllerLibraries_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ReloadControllerLibraries_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ReloadControllerLibraries_Response__Array_to_Go(goSlice []ReloadControllerLibraries_Response, cSlice []CReloadControllerLibraries_Response) {
	for i := 0; i < len(cSlice); i++ {
		ReloadControllerLibraries_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ReloadControllerLibraries_Response__Array_to_C(cSlice []CReloadControllerLibraries_Response, goSlice []ReloadControllerLibraries_Response) {
	for i := 0; i < len(goSlice); i++ {
		ReloadControllerLibraries_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
