// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	lifecycle_msgs_msg "msgs/lifecycle_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/set_hardware_component_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/SetHardwareComponentState_Request", SetHardwareComponentState_RequestTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/SetHardwareComponentState_Request", SetHardwareComponentState_RequestTypeSupport)
}

type SetHardwareComponentState_Request struct {
	Name string `yaml:"name"`
	TargetState lifecycle_msgs_msg.State `yaml:"target_state"`
}

// NewSetHardwareComponentState_Request creates a new SetHardwareComponentState_Request with default values.
func NewSetHardwareComponentState_Request() *SetHardwareComponentState_Request {
	self := SetHardwareComponentState_Request{}
	self.SetDefaults()
	return &self
}

func (t *SetHardwareComponentState_Request) Clone() *SetHardwareComponentState_Request {
	c := &SetHardwareComponentState_Request{}
	c.Name = t.Name
	c.TargetState = *t.TargetState.Clone()
	return c
}

func (t *SetHardwareComponentState_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetHardwareComponentState_Request) SetDefaults() {
	t.Name = ""
	t.TargetState.SetDefaults()
}

func (t *SetHardwareComponentState_Request) GetTypeSupport() types.MessageTypeSupport {
	return SetHardwareComponentState_RequestTypeSupport
}

// SetHardwareComponentState_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetHardwareComponentState_RequestPublisher struct {
	*rclgo.Publisher
}

// NewSetHardwareComponentState_RequestPublisher creates and returns a new publisher for the
// SetHardwareComponentState_Request
func NewSetHardwareComponentState_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetHardwareComponentState_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetHardwareComponentState_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetHardwareComponentState_RequestPublisher{pub}, nil
}

func (p *SetHardwareComponentState_RequestPublisher) Publish(msg *SetHardwareComponentState_Request) error {
	return p.Publisher.Publish(msg)
}

// SetHardwareComponentState_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetHardwareComponentState_RequestSubscription struct {
	*rclgo.Subscription
}

// SetHardwareComponentState_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a SetHardwareComponentState_RequestSubscription.
type SetHardwareComponentState_RequestSubscriptionCallback func(msg *SetHardwareComponentState_Request, info *rclgo.MessageInfo, err error)

// NewSetHardwareComponentState_RequestSubscription creates and returns a new subscription for the
// SetHardwareComponentState_Request
func NewSetHardwareComponentState_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetHardwareComponentState_RequestSubscriptionCallback) (*SetHardwareComponentState_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetHardwareComponentState_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetHardwareComponentState_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetHardwareComponentState_RequestSubscription{sub}, nil
}

func (s *SetHardwareComponentState_RequestSubscription) TakeMessage(out *SetHardwareComponentState_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetHardwareComponentState_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetHardwareComponentState_RequestSlice(dst, src []SetHardwareComponentState_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetHardwareComponentState_RequestTypeSupport types.MessageTypeSupport = _SetHardwareComponentState_RequestTypeSupport{}

type _SetHardwareComponentState_RequestTypeSupport struct{}

func (t _SetHardwareComponentState_RequestTypeSupport) New() types.Message {
	return NewSetHardwareComponentState_Request()
}

func (t _SetHardwareComponentState_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__SetHardwareComponentState_Request
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__SetHardwareComponentState_Request__create())
}

func (t _SetHardwareComponentState_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__SetHardwareComponentState_Request__destroy((*C.controller_manager_msgs__srv__SetHardwareComponentState_Request)(pointer_to_free))
}

func (t _SetHardwareComponentState_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetHardwareComponentState_Request)
	mem := (*C.controller_manager_msgs__srv__SetHardwareComponentState_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.name), m.Name)
	lifecycle_msgs_msg.StateTypeSupport.AsCStruct(unsafe.Pointer(&mem.target_state), &m.TargetState)
}

func (t _SetHardwareComponentState_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetHardwareComponentState_Request)
	mem := (*C.controller_manager_msgs__srv__SetHardwareComponentState_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Name, unsafe.Pointer(&mem.name))
	lifecycle_msgs_msg.StateTypeSupport.AsGoStruct(&m.TargetState, unsafe.Pointer(&mem.target_state))
}

func (t _SetHardwareComponentState_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__SetHardwareComponentState_Request())
}

type CSetHardwareComponentState_Request = C.controller_manager_msgs__srv__SetHardwareComponentState_Request
type CSetHardwareComponentState_Request__Sequence = C.controller_manager_msgs__srv__SetHardwareComponentState_Request__Sequence

func SetHardwareComponentState_Request__Sequence_to_Go(goSlice *[]SetHardwareComponentState_Request, cSlice CSetHardwareComponentState_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetHardwareComponentState_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetHardwareComponentState_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetHardwareComponentState_Request__Sequence_to_C(cSlice *CSetHardwareComponentState_Request__Sequence, goSlice []SetHardwareComponentState_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__SetHardwareComponentState_Request)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__SetHardwareComponentState_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetHardwareComponentState_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetHardwareComponentState_Request__Array_to_Go(goSlice []SetHardwareComponentState_Request, cSlice []CSetHardwareComponentState_Request) {
	for i := 0; i < len(cSlice); i++ {
		SetHardwareComponentState_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetHardwareComponentState_Request__Array_to_C(cSlice []CSetHardwareComponentState_Request, goSlice []SetHardwareComponentState_Request) {
	for i := 0; i < len(goSlice); i++ {
		SetHardwareComponentState_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
