// Code generated by rclgo-gen. DO NOT EDIT.

package controller_manager_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <controller_manager_msgs/srv/unload_controller.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("controller_manager_msgs/UnloadController_Response", UnloadController_ResponseTypeSupport)
	typemap.RegisterMessage("controller_manager_msgs/srv/UnloadController_Response", UnloadController_ResponseTypeSupport)
}

type UnloadController_Response struct {
	Ok bool `yaml:"ok"`
}

// NewUnloadController_Response creates a new UnloadController_Response with default values.
func NewUnloadController_Response() *UnloadController_Response {
	self := UnloadController_Response{}
	self.SetDefaults()
	return &self
}

func (t *UnloadController_Response) Clone() *UnloadController_Response {
	c := &UnloadController_Response{}
	c.Ok = t.Ok
	return c
}

func (t *UnloadController_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *UnloadController_Response) SetDefaults() {
	t.Ok = false
}

func (t *UnloadController_Response) GetTypeSupport() types.MessageTypeSupport {
	return UnloadController_ResponseTypeSupport
}

// UnloadController_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type UnloadController_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewUnloadController_ResponsePublisher creates and returns a new publisher for the
// UnloadController_Response
func NewUnloadController_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*UnloadController_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, UnloadController_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &UnloadController_ResponsePublisher{pub}, nil
}

func (p *UnloadController_ResponsePublisher) Publish(msg *UnloadController_Response) error {
	return p.Publisher.Publish(msg)
}

// UnloadController_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type UnloadController_ResponseSubscription struct {
	*rclgo.Subscription
}

// UnloadController_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a UnloadController_ResponseSubscription.
type UnloadController_ResponseSubscriptionCallback func(msg *UnloadController_Response, info *rclgo.MessageInfo, err error)

// NewUnloadController_ResponseSubscription creates and returns a new subscription for the
// UnloadController_Response
func NewUnloadController_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback UnloadController_ResponseSubscriptionCallback) (*UnloadController_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg UnloadController_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, UnloadController_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &UnloadController_ResponseSubscription{sub}, nil
}

func (s *UnloadController_ResponseSubscription) TakeMessage(out *UnloadController_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneUnloadController_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneUnloadController_ResponseSlice(dst, src []UnloadController_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var UnloadController_ResponseTypeSupport types.MessageTypeSupport = _UnloadController_ResponseTypeSupport{}

type _UnloadController_ResponseTypeSupport struct{}

func (t _UnloadController_ResponseTypeSupport) New() types.Message {
	return NewUnloadController_Response()
}

func (t _UnloadController_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.controller_manager_msgs__srv__UnloadController_Response
	return (unsafe.Pointer)(C.controller_manager_msgs__srv__UnloadController_Response__create())
}

func (t _UnloadController_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.controller_manager_msgs__srv__UnloadController_Response__destroy((*C.controller_manager_msgs__srv__UnloadController_Response)(pointer_to_free))
}

func (t _UnloadController_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*UnloadController_Response)
	mem := (*C.controller_manager_msgs__srv__UnloadController_Response)(dst)
	mem.ok = C.bool(m.Ok)
}

func (t _UnloadController_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*UnloadController_Response)
	mem := (*C.controller_manager_msgs__srv__UnloadController_Response)(ros2_message_buffer)
	m.Ok = bool(mem.ok)
}

func (t _UnloadController_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__controller_manager_msgs__srv__UnloadController_Response())
}

type CUnloadController_Response = C.controller_manager_msgs__srv__UnloadController_Response
type CUnloadController_Response__Sequence = C.controller_manager_msgs__srv__UnloadController_Response__Sequence

func UnloadController_Response__Sequence_to_Go(goSlice *[]UnloadController_Response, cSlice CUnloadController_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]UnloadController_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		UnloadController_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func UnloadController_Response__Sequence_to_C(cSlice *CUnloadController_Response__Sequence, goSlice []UnloadController_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.controller_manager_msgs__srv__UnloadController_Response)(C.malloc(C.sizeof_struct_controller_manager_msgs__srv__UnloadController_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		UnloadController_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func UnloadController_Response__Array_to_Go(goSlice []UnloadController_Response, cSlice []CUnloadController_Response) {
	for i := 0; i < len(cSlice); i++ {
		UnloadController_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func UnloadController_Response__Array_to_C(cSlice []CUnloadController_Response, goSlice []UnloadController_Response) {
	for i := 0; i < len(goSlice); i++ {
		UnloadController_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
