// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/srv/query_calibration_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/QueryCalibrationState_Response", QueryCalibrationState_ResponseTypeSupport)
	typemap.RegisterMessage("control_msgs/srv/QueryCalibrationState_Response", QueryCalibrationState_ResponseTypeSupport)
}

type QueryCalibrationState_Response struct {
	IsCalibrated bool `yaml:"is_calibrated"`
}

// NewQueryCalibrationState_Response creates a new QueryCalibrationState_Response with default values.
func NewQueryCalibrationState_Response() *QueryCalibrationState_Response {
	self := QueryCalibrationState_Response{}
	self.SetDefaults()
	return &self
}

func (t *QueryCalibrationState_Response) Clone() *QueryCalibrationState_Response {
	c := &QueryCalibrationState_Response{}
	c.IsCalibrated = t.IsCalibrated
	return c
}

func (t *QueryCalibrationState_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *QueryCalibrationState_Response) SetDefaults() {
	t.IsCalibrated = false
}

func (t *QueryCalibrationState_Response) GetTypeSupport() types.MessageTypeSupport {
	return QueryCalibrationState_ResponseTypeSupport
}

// QueryCalibrationState_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type QueryCalibrationState_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewQueryCalibrationState_ResponsePublisher creates and returns a new publisher for the
// QueryCalibrationState_Response
func NewQueryCalibrationState_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*QueryCalibrationState_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, QueryCalibrationState_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &QueryCalibrationState_ResponsePublisher{pub}, nil
}

func (p *QueryCalibrationState_ResponsePublisher) Publish(msg *QueryCalibrationState_Response) error {
	return p.Publisher.Publish(msg)
}

// QueryCalibrationState_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type QueryCalibrationState_ResponseSubscription struct {
	*rclgo.Subscription
}

// QueryCalibrationState_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a QueryCalibrationState_ResponseSubscription.
type QueryCalibrationState_ResponseSubscriptionCallback func(msg *QueryCalibrationState_Response, info *rclgo.MessageInfo, err error)

// NewQueryCalibrationState_ResponseSubscription creates and returns a new subscription for the
// QueryCalibrationState_Response
func NewQueryCalibrationState_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback QueryCalibrationState_ResponseSubscriptionCallback) (*QueryCalibrationState_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg QueryCalibrationState_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, QueryCalibrationState_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &QueryCalibrationState_ResponseSubscription{sub}, nil
}

func (s *QueryCalibrationState_ResponseSubscription) TakeMessage(out *QueryCalibrationState_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneQueryCalibrationState_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneQueryCalibrationState_ResponseSlice(dst, src []QueryCalibrationState_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var QueryCalibrationState_ResponseTypeSupport types.MessageTypeSupport = _QueryCalibrationState_ResponseTypeSupport{}

type _QueryCalibrationState_ResponseTypeSupport struct{}

func (t _QueryCalibrationState_ResponseTypeSupport) New() types.Message {
	return NewQueryCalibrationState_Response()
}

func (t _QueryCalibrationState_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__srv__QueryCalibrationState_Response
	return (unsafe.Pointer)(C.control_msgs__srv__QueryCalibrationState_Response__create())
}

func (t _QueryCalibrationState_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__srv__QueryCalibrationState_Response__destroy((*C.control_msgs__srv__QueryCalibrationState_Response)(pointer_to_free))
}

func (t _QueryCalibrationState_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*QueryCalibrationState_Response)
	mem := (*C.control_msgs__srv__QueryCalibrationState_Response)(dst)
	mem.is_calibrated = C.bool(m.IsCalibrated)
}

func (t _QueryCalibrationState_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*QueryCalibrationState_Response)
	mem := (*C.control_msgs__srv__QueryCalibrationState_Response)(ros2_message_buffer)
	m.IsCalibrated = bool(mem.is_calibrated)
}

func (t _QueryCalibrationState_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__srv__QueryCalibrationState_Response())
}

type CQueryCalibrationState_Response = C.control_msgs__srv__QueryCalibrationState_Response
type CQueryCalibrationState_Response__Sequence = C.control_msgs__srv__QueryCalibrationState_Response__Sequence

func QueryCalibrationState_Response__Sequence_to_Go(goSlice *[]QueryCalibrationState_Response, cSlice CQueryCalibrationState_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]QueryCalibrationState_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		QueryCalibrationState_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func QueryCalibrationState_Response__Sequence_to_C(cSlice *CQueryCalibrationState_Response__Sequence, goSlice []QueryCalibrationState_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__srv__QueryCalibrationState_Response)(C.malloc(C.sizeof_struct_control_msgs__srv__QueryCalibrationState_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		QueryCalibrationState_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func QueryCalibrationState_Response__Array_to_Go(goSlice []QueryCalibrationState_Response, cSlice []CQueryCalibrationState_Response) {
	for i := 0; i < len(cSlice); i++ {
		QueryCalibrationState_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func QueryCalibrationState_Response__Array_to_C(cSlice []CQueryCalibrationState_Response, goSlice []QueryCalibrationState_Response) {
	for i := 0; i < len(goSlice); i++ {
		QueryCalibrationState_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
