// Code generated by rclgo-gen. DO NOT EDIT.

package control_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <control_msgs/srv/query_trajectory_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("control_msgs/QueryTrajectoryState_Request", QueryTrajectoryState_RequestTypeSupport)
	typemap.RegisterMessage("control_msgs/srv/QueryTrajectoryState_Request", QueryTrajectoryState_RequestTypeSupport)
}

type QueryTrajectoryState_Request struct {
	Time builtin_interfaces_msg.Time `yaml:"time"`
}

// NewQueryTrajectoryState_Request creates a new QueryTrajectoryState_Request with default values.
func NewQueryTrajectoryState_Request() *QueryTrajectoryState_Request {
	self := QueryTrajectoryState_Request{}
	self.SetDefaults()
	return &self
}

func (t *QueryTrajectoryState_Request) Clone() *QueryTrajectoryState_Request {
	c := &QueryTrajectoryState_Request{}
	c.Time = *t.Time.Clone()
	return c
}

func (t *QueryTrajectoryState_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *QueryTrajectoryState_Request) SetDefaults() {
	t.Time.SetDefaults()
}

func (t *QueryTrajectoryState_Request) GetTypeSupport() types.MessageTypeSupport {
	return QueryTrajectoryState_RequestTypeSupport
}

// QueryTrajectoryState_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type QueryTrajectoryState_RequestPublisher struct {
	*rclgo.Publisher
}

// NewQueryTrajectoryState_RequestPublisher creates and returns a new publisher for the
// QueryTrajectoryState_Request
func NewQueryTrajectoryState_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*QueryTrajectoryState_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, QueryTrajectoryState_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &QueryTrajectoryState_RequestPublisher{pub}, nil
}

func (p *QueryTrajectoryState_RequestPublisher) Publish(msg *QueryTrajectoryState_Request) error {
	return p.Publisher.Publish(msg)
}

// QueryTrajectoryState_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type QueryTrajectoryState_RequestSubscription struct {
	*rclgo.Subscription
}

// QueryTrajectoryState_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a QueryTrajectoryState_RequestSubscription.
type QueryTrajectoryState_RequestSubscriptionCallback func(msg *QueryTrajectoryState_Request, info *rclgo.MessageInfo, err error)

// NewQueryTrajectoryState_RequestSubscription creates and returns a new subscription for the
// QueryTrajectoryState_Request
func NewQueryTrajectoryState_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback QueryTrajectoryState_RequestSubscriptionCallback) (*QueryTrajectoryState_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg QueryTrajectoryState_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, QueryTrajectoryState_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &QueryTrajectoryState_RequestSubscription{sub}, nil
}

func (s *QueryTrajectoryState_RequestSubscription) TakeMessage(out *QueryTrajectoryState_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneQueryTrajectoryState_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneQueryTrajectoryState_RequestSlice(dst, src []QueryTrajectoryState_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var QueryTrajectoryState_RequestTypeSupport types.MessageTypeSupport = _QueryTrajectoryState_RequestTypeSupport{}

type _QueryTrajectoryState_RequestTypeSupport struct{}

func (t _QueryTrajectoryState_RequestTypeSupport) New() types.Message {
	return NewQueryTrajectoryState_Request()
}

func (t _QueryTrajectoryState_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.control_msgs__srv__QueryTrajectoryState_Request
	return (unsafe.Pointer)(C.control_msgs__srv__QueryTrajectoryState_Request__create())
}

func (t _QueryTrajectoryState_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.control_msgs__srv__QueryTrajectoryState_Request__destroy((*C.control_msgs__srv__QueryTrajectoryState_Request)(pointer_to_free))
}

func (t _QueryTrajectoryState_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*QueryTrajectoryState_Request)
	mem := (*C.control_msgs__srv__QueryTrajectoryState_Request)(dst)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.time), &m.Time)
}

func (t _QueryTrajectoryState_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*QueryTrajectoryState_Request)
	mem := (*C.control_msgs__srv__QueryTrajectoryState_Request)(ros2_message_buffer)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Time, unsafe.Pointer(&mem.time))
}

func (t _QueryTrajectoryState_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__control_msgs__srv__QueryTrajectoryState_Request())
}

type CQueryTrajectoryState_Request = C.control_msgs__srv__QueryTrajectoryState_Request
type CQueryTrajectoryState_Request__Sequence = C.control_msgs__srv__QueryTrajectoryState_Request__Sequence

func QueryTrajectoryState_Request__Sequence_to_Go(goSlice *[]QueryTrajectoryState_Request, cSlice CQueryTrajectoryState_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]QueryTrajectoryState_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		QueryTrajectoryState_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func QueryTrajectoryState_Request__Sequence_to_C(cSlice *CQueryTrajectoryState_Request__Sequence, goSlice []QueryTrajectoryState_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.control_msgs__srv__QueryTrajectoryState_Request)(C.malloc(C.sizeof_struct_control_msgs__srv__QueryTrajectoryState_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		QueryTrajectoryState_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func QueryTrajectoryState_Request__Array_to_Go(goSlice []QueryTrajectoryState_Request, cSlice []CQueryTrajectoryState_Request) {
	for i := 0; i < len(cSlice); i++ {
		QueryTrajectoryState_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func QueryTrajectoryState_Request__Array_to_C(cSlice []CQueryTrajectoryState_Request, goSlice []QueryTrajectoryState_Request) {
	for i := 0; i < len(goSlice); i++ {
		QueryTrajectoryState_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
